### ISSUE TITLE
在Chrome63开发环境下调试vite项目

### ISSUE THREAD

**Issue by pscweek** [vitejs/vite-plugin-vue#364] opened 2024-03-01 03:23 UTC
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

node 16.16.0
vite 4.1.0
vue 3.2.45
typescript 4.9.3
npm run dev 运行项目后，在Chrome63版本打开，显示空白页，并且有报错：
![image](https://github.com/vitejs/vite-plugin-vue/assets/100405693/6d83f433-0bf5-4fea-9dde-ae0435a9da85)
![image](https://github.com/vitejs/vite-plugin-vue/assets/100405693/5dd7fbdb-38ac-4151-9449-9db18e3568ca)
目的就是在Chrome63开发环境下调试vite项目，注意不是生产环境。

### Reproduction

https://github.com/LLLuojp/test_project

### System Info

```shell
Uncaught SyntaxError: Unexpected token .
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment] 2024-03-11 07:48
Duplicate of https://github.com/vitejs/vite/issues/16066

**Closed by sapphi-red** 2024-03-11 07:48 UTC
Labels: pending triage
