### ISSUE TITLE
`@vitejs/plugin-vue` SSR not working properly with `build.rollupOptions.external`

### ISSUE THREAD

**Issue by AaronBeaudoin** [vitejs/vite-plugin-vue#29] opened 2022-09-23 15:05 UTC
### Describe the bug

Suppose I have a minimal `App.vue` like this:

```vue
<template>
  <img src="/test">
</template>
```

The URL `/test` is not a module in my project but an image I'd like to just trust will be there at runtime in production. To do this, `build.rollupOptions.external` seems to be what I would want. So I set the option to simply `["/test"]`.

When I then build my project with `npm run build`, I get this SSR output (run reproduction for complete output):

```js
import { useSSRContext, mergeProps, createSSRApp } from "vue";
import { ssrRenderAttrs, renderToString } from "vue/server-renderer";
import _imports_0 from "../../../../../../test"; // <-- What in the world is this?

...

function _sfc_ssrRender(_ctx, _push, _parent, _attrs) {
  _push(`<img${ssrRenderAttrs(mergeProps({ src: _imports_0 }, _attrs))}>`);
}
```

This is totally not what I would want/expect. In the [Vue SFC Playground](https://sfc.vuejs.org/#__SSR__eNp9jcsOgkAMRX9l0jXM7Ama+B/dIFaEOI+0BReEf3fGsDCasGtPb89d4ZKSXWaCBloln56d0hmDMe3oByPcnxCckihCxm0e9wxUMPoUWWvfJTtJDFmxlk/cD4LQmA8pLHeUHeGhmqRxTu59KZ7ERh5cnizPQUdPlsTXV44vIc5ihOrL4TJciGumcCMmPnL+RP+8Rbth2GB7A9vJWrU=) this is the complete output I get:

```js
const __sfc__ = {}
import { mergeProps as _mergeProps } from "vue"
import { ssrRenderAttrs as _ssrRenderAttrs } from "vue/server-renderer"
function ssrRender(_ctx, _push, _parent, _attrs) {
  _push(`<img${_ssrRenderAttrs(_mergeProps({ src: "/test" }, _attrs))}>`)
}
__sfc__.ssrRender = ssrRender
__sfc__.__file = "App.vue"
export default __sfc__
```

The key difference is:

```js
mergeProps({ src: "/test" }, _attrs) // <-- CORRECT
```

Versus:

```js
import _imports_0 from "../../../../../../test"; // <-- WTF?
mergeProps({ src: _imports_0 }, _attrs)
```

### Reproduction

https://github.com/AaronBeaudoin/vite-plugin-vue-issue-external

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 82.14 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.volta/tools/image/node/16.17.0/bin/node
    npm: 8.15.0 - ~/.volta/tools/image/node/16.17.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 15.6
  npmPackages:
    @vitejs/plugin-vue: ^3.1.0 => 3.1.0 
    vite: ^3.0.4 => 3.0.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by edison1105** [comment] 2024-09-25 02:40
Closing as it can't reproduce with the follow versions:
```json  
 "devDependencies": {
    "vite": "5.4.7"
  },
  "dependencies": {
    "@vitejs/plugin-vue": "5.1.4"
  }
```

**Closed by edison1105** 2024-09-25 02:40 UTC
Labels: pending triage
