### ISSUE TITLE
Class names hydration mismatches when using SSR and SCSS styles with `module` 

### ISSUE THREAD

**Issue by Gwynerva** [vitejs/vite-plugin-vue#477] opened 2024-11-20 17:40 UTC
### Describe the bug

Without module attribute on <style> Vue SSR correctly handles updates to .scss files that are imported via @use ... at-rule.
However, with module attribte it fails to watch changes to style files or something else breaks with hydration mismatches related to hashed class names so only making manual changes to .vue file will re-sync the updates.

It is also not related to flexible path options when using @use. The bug occurs no matter how you use style files: with .scss extension and without it, omitting _ at the beginning or not.

### Reproduction

https://stackblitz.com/edit/github-bea9um

### Steps to reproduce

Just create an external `.scss` file, define any mixin and then `@include` that mixin in any `.vue` file `<style lang="scss" module>` tag.
Changing the `.scss` fill will break **all** files that `@use` this style file.

### System Info

```shell
Everywhere
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vite.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vite.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by edison1105** [comment] 2024-11-21 06:19
duplicate of #146 
The root cause is that the HMR reload triggers hydration. 
This is a bug in vuejs/core, I will create a PR to fix this.

**Closed by edison1105** 2024-11-21 06:19 UTC
Labels: pending triage
