### ISSUE TITLE
No loader is configured for ".vue" files

### ISSUE THREAD

**Issue by mjx666** [vitejs/vite-plugin-vue#150] opened 2023-04-13 00:18 UTC
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

vite4+ts项目正确配置了vite-plugin-vue插件，但是还是运行终端node环境还是报错找不到vue文件的loader，在浏览器项目功能是正常的

### Reproduction

need reproduction

### Steps to reproduce

pnpm i

### System Info

```shell
"@vitejs/plugin-vue": "^4.0.0",
"vite": "^4.1.0",
"node": "16.13.1"
```

### Used Package Manager

pnpm

### Logs

![image](https://user-images.githubusercontent.com/20264797/231613238-c7fb517c-cb85-4a37-b775-6d6f91b2b02e.png)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment] 2023-04-17 02:38
Duplicate of #26

**Closed by sapphi-red** 2023-04-17 02:38 UTC
Labels: pending triage
