### ISSUE TITLE
when use <script lang="tsx" setup> with template. HMR can not resolve import component using in template

### ISSUE THREAD

**Issue by we125182** [vitejs/vite-plugin-vue#22] opened 2022-06-26 03:32 UTC
### Describe the bug

after project run. replace App.vue<script>code with follows
```vue
<script setup lang="tsx">
import { Search } from '@element-plus/icons-vue'
// import { Apple } from '@element-plus/icons-vue'

import RenderComp from './components/RenderComp'

const label = () => (<div>test</div>)
</script>

<template>
  <RenderComp :label="label" />
  <Search />
  <!-- <Apple /> -->
</template>
```
>**warning**
only after the project running, import new component using in template. the problem appears.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-qrc4zw?file=src/App.vue

### System Info

```shell
System:
    OS: macOS 11.6.5
    CPU: (8) x64 Apple M1
    Memory: 31.31 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 95.0
    Safari: 15.4
  npmPackages:
    @vitejs/plugin-vue: ^2.3.3 => 2.3.3 
    @vitejs/plugin-vue-jsx: ^1.3.10 => 1.3.10 
    vite: ^2.9.12 => 2.9.12
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by edison1105** [comment] 2024-09-25 03:23
Closing as it can't reproduce with:
```json
  "dependencies": {
    "vue": "3.5.8"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "5.1.4",
    "@vitejs/plugin-vue-jsx": " 4.0.1",
    "vite": "5.4.7",
  }
```

**Closed by edison1105** 2024-09-25 03:23 UTC
Labels: feat: hmr, p3-minor-bug :hammer:
