### ISSUE TITLE
Render icons from @ant-design/icons-vue once when using ssr

### ISSUE THREAD

**Issue by wheeljs** [vitejs/vite-plugin-vue#14] opened 2022-06-29 04:38 UTC
#### Steps to reproduce
1. Setup a vite with ssr project by ['vite-ssr'](https://github.com/frandiox/vite-ssr#installation).
2. Add ant-design-vue@^3.2.7
3. Add `<a-select mode="multiple">` into component, select multiple options. It renders close icon for selected options in input and checked icon in popover, but each icon just render once.
4. Only one selected options in `<a-select>` has remove icon.

#### What is expected?
All selected options should have remove icon after its label whether ssr or not.(Works fine in normally command `vite`)

#### What is actually happening?
Only one selected options in `<a-select>` has remove icon.

---

I thought this may be a bug of vite-ssr, so I have also tested in [vite-plugin-ssr](https://vite-plugin-ssr.com/)([reproduction link](https://stackblitz.com/edit/express-simple-k7f6dk?file=pages%2Findex%2Findex.page.vue)), problems still exist, so I think this may be a vite's bug.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-evglmf?file=src%2FApp.vue

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 2.23 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 10.23.2 - ~/n/bin/node
    Yarn: 1.22.17 - ~/n/bin/yarn
    npm: 6.14.10 - ~/n/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 100.0.2
    Safari: 15.5
  npmPackages:
    @vitejs/plugin-vue: ^2.3.3 => 2.3.3
    vite: ^2.9.12 => 2.9.12
```

### Used Package Manager

npm

### Logs

<details>
<summary>Click to expand!</summary>

```shell
 vite v2.9.12 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

 -- SSR mode ready in 3313ms.

vite-ssr doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
```
</details> 

Sorry for my English.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by daomiaru** [comment] 2023-06-05 07:12
@wheeljs 你好我这边在使用nuxt3进行服务端渲染时遇到了和你一样的问题，请问你这里解决了吗

**Comment by edison1105** [comment] 2024-09-25 03:16
Closing as it can't reproduce with the latest version.
```json
    "ant-design-vue": "4.2.5",
    "vue": "3.5.8",
```

**Closed by edison1105** 2024-09-25 03:16 UTC
Labels: feat: ssr
