### ISSUE TITLE
Vite Config doesnt work with dev mode and Ngnix Proxy-Passs in Dokcer

### ISSUE THREAD

**Issue by aliosmanmenekse** [vitejs/vite-plugin-vue#45] opened 2022-12-07 19:49 UTC
### Related plugins

- [ ] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

This config works for preview mode but it does not work dev mode. I want to serve my application when user enters the url `https://qaautomation1.com/architect`. I believe there is a problem here. Please check and comment here 

![image](https://user-images.githubusercontent.com/29566255/206280096-ca4b8421-2d82-4f80-89a7-97490b923824.png)

My old vue-cli config
```
module.exports = {
    publicPath: '/architect/',
    devServer: {
        public: '0.0.0.0/architect/',
        disableHostCheck: true,
        host: '0.0.0.0',
        https: false,
        port: 23310
    }
}
```

My new vite config

```
base: /architect/',
server: {
    host: '0.0.0.0',
    https: false,
    port: 23310,
},
```

My Ngnix config
```

location ^~ /architect/ {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://aristo/architect/;
    }
```

### Reproduction

-----

### Steps to reproduce

--------

### System Info

```shell
-----
```

### Used Package Manager

npm

### Logs

-----

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment] 2022-12-11 09:53
Duplicate of https://github.com/vitejs/vite/issues/6596

**Closed by sapphi-red** 2022-12-11 09:53 UTC
Labels: pending triage
