### ISSUE TITLE
[Production Problem] Problems when building SFCs with generic props

### ISSUE THREAD

**Issue by 0x00A1FA** [vitejs/vite-plugin-vue#165] opened 2023-05-05 09:33 UTC
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

Hi,

I have a few SFCs with generic props (which suck in Vue right now, by the way; can't wait for Vue 3.3) and, when I build them, the filenames of those SFCs are similar to what @dflock (genius) mentioned in his comment at https://github.com/vitejs/vite-plugin-vue/issues/19#issuecomment-1471409276.

Please improve the filename generation.

Thanks!

### Reproduction

https://github.com/vitejs/vite-plugin-vue/issues/19#issuecomment-1471409276

### System Info

```shell
Micro Soft Window 10
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment] 2023-05-08 02:14
Duplicate of #19

**Closed by sapphi-red** 2023-05-08 02:14 UTC
Labels: pending triage
