### ISSUE TITLE
Render function not injected when default export is not accessed, inconsistent behavior between dev and build.

### ISSUE THREAD

**Issue by zhangyx1998** [vitejs/vite-plugin-vue#233] opened 2023-08-20 23:44 UTC
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

The render function will **NOT** be injected in any of the conditions described [below](#exploration).

### To make sense of my use case

I am trying to wrap some of my components using a "factory method". The factory method will return a callback function that injects some standard methods, variables and emits into wrapped components and then render the component in an enclosing window.

Here is a minimal example of my factory method:

```js
function WindowFactory(component) {
    // Extract setup and emits from the original component
    const {
        setup = () => {},
        emits = [],
        ...others
    } = component;
    // Returns a callback to launch the window
    return function launch(...args) {
        // "Injected" component is prepared here
        const windowContent = {
            // This is the "hijacked" setup method
            setup() {
                return {
                    injectedMethod() {},
                    // Arguments are passed to the original setup method
                    ...setup(...args),
                };
            },
            // Mix injected emits into the component's original emits
            emits: ['injectedEmits', ...emits],
        };
        // Launch the window, and return a promise that resolves when the window is closed
        return new Promise((resolve, reject) => { /* ... */ });
    };
}
```

### A demonstrative example that works in vite dev but fails in distribution:

```vue
<template> ... </template>

<script>
import { defineComponent } from 'vue';
import WindowFactory from '...';
// The component to be rendered inside a window
const component = defineComponent({ /* ... */ });
// This is the real export that will be called by other code
export const launchWindow = WindowFactory(component);
</script>
```

> The above function `launchWindow`, when invoked inside a bundled distribution, will not produce any error, and will neither produce any renderings.

<a id="exploration"></a>

### My exploration to this problem

After some experiment, I found out the following facts:

1. The render function would **NOT** exist if I do not export it as default.

    ```js
    // This dose NOT work:
    export const component = defineComponent({ /* ... */ });
    export const launchWindow = WindowFactory(component);
    // ('render' in component) === false
    console.log(component)
    ```

1. Even if I export the component as default, it will **NOT** have render function when I do not access it in other contexts.

    ```js
    // example.vue
    // This dose NOT work:
    export const component = defineComponent({ /* ... */ });
    export const launchWindow = WindowFactory(component);
    export default component;
    // ('render' in component) === false
    console.log(component)
    ```

1. Accessing named exports (`export const ...`) from outside the SFC will still **NOT** produce the render function.

    ```js
    // another_file.js
    // This dose NOT work:
    import { component } from './example.vue';
    // ('render' in component) === false
    console.log(component)
    ```

1. As long as the default exported component is accessed **OUTSIDE** its SFC context (`example.vue`),
it will get a render function.

    ```js
    // yet_another_file.js
    // This works:
    import component from './example.vue';
    // ('render' in component) === true
    console.log(component)
    ```

    And after accessing the default export component, the in-context component will also magically receive a render function.

### Real-word issue impact

This issue was found while developing a window framework for a web app.

+ The problematic code can be found in [Random Student Picker`Commit ae16206`](https://github.com/zhangyx1998/random-student-picker/commit/ae1620641dba875b0ac3e9988e82875f41fad720).

    To reproduce the issue:

    ```sh
    # git clone https://github.com/zhangyx1998/random-student-picker.git && cd random-student-picker
    git checkout ae1620641dba875b0ac3e9988e82875f41fad720;
    SRV_PORT=8080 make demo;
    ```

    The project will be served at local port `8080` or the port of your select.

+ A sample fix can be found in [Random Student Picker`Commit eeeb835`](https://github.com/zhangyx1998/random-student-picker/commit/eeeb8356149bda470b3c3c3ac50bcec200705792)

    To view the desired behavior:

    ```sh
    # git clone https://github.com/zhangyx1998/random-student-picker.git && cd random-student-picker
    git checkout eeeb8356149bda470b3c3c3ac50bcec200705792;
    SRV_PORT=8080 make demo;
    ```

    The project will be served at local port `8080` or the port of your select.

| Problematic | Desired |
|:-----------:|:--------:|
| <img width="320px" alt="Problematic Screenshot" src="https://github.com/vitejs/vite-plugin-vue/assets/37485759/5330986b-3d97-40dd-bd66-266b5b750aa6"> | <img width="320px" alt="Desired Screenshot" src="https://github.com/vitejs/vite-plugin-vue/assets/37485759/b48acd43-2901-4954-b608-6d42ca298827"> |

I would have to create separate files for functionalities that serve a single purpose. It works but also makes stuff scatter around. I have to maintain multiple files when I want to make changes to a single feature.

### Desired behavior

The most intuitive behavior I would expect is `vue-plugin-vite` automatically inject compiled render function into whichever object that is wrapped with `defineComponent()`. Regardless of whether and how the component is exported.
In this way more flexibility would be given to the developer.

I looked into `src/plugin-vue` in order to understand the things happened under the hood, but was not able to identify the code related to injecting render functions. I can try to fix it if someone tells me where to look at.

BTW, I am not so sure if this problem has anything to do with `rollup`'s tree shaking. And I did not have the time to reproduce this with `webpack`. So it is possible I filed the issue in the wrong project. Please let me know if that is the case.

### Reproduction

https://github.com/zhangyx1998/vite-plugin-vue-issue-reproduction

### Steps to reproduce

+ `npm install`
+ `npm run dev` will show all 3 components.
+ `npm run preview` will only show component A and C.
+ Use developer tools to see the components logged to console. You should notice the missing render function.

> P.S. Screenshots have been included in README.

### System Info

```shell
System:
  OS: macOS 13.4.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 159.50 MB / 32.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.5.0 - /opt/homebrew/bin/node
  npm: 9.8.0 - /opt/homebrew/bin/npm
Browsers:
  Chrome: 115.0.5790.170
  Safari: 16.5.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhangyx1998** [comment] 2023-08-21 02:58
I dug a little deeper and found [`vuejs/core/packages/compiler-sfc`](https://github.com/vuejs/core/tree/main/packages/compiler-sfc) that explains where and how the render function would be injected.

I am suspecting that my problem could be caused by the `facade module` never get a chance to run if I do not access the default export provided by it.

Please leave some comment on this, and please let me know if I should file shit issue on [vuejs/core](https://github.com/vuejs/core) instead.

**Comment by zhangyx1998** [comment] 2023-08-21 05:43
I have confirmed that this issue should be submitted to `vuejs/core`. I will resubmit it there and close this one.

**Comment by zhangyx1998** [comment] 2023-08-22 04:20
It turns out to be relevant, please see [this comment](https://github.com/vuejs/core/issues/9011#issuecomment-1687388624).

I am reopening this issue hoping to draw someone's attention on it.

**Comment by sapphi-red** [comment] 2023-10-12 14:15
Duplicate of #11

**Closed by sapphi-red** 2023-10-12 14:15 UTC
Labels: pending triage
