### ISSUE TITLE
Debugging vite+vue+typescript using HMR is broken. Breakpoint on incorrect line numbers

### ISSUE THREAD

**Issue by hspaay** [vitejs/vite-plugin-vue#33] opened 2021-12-01 05:39 UTC
### Describe the bug

Trying to debug a vite+vue+ts app doesn't work for me. As soon as HMR runs the vscode debugger no longer stops on breakpoints. Possible the sourcemap gets out of sync.

In addition, chrome devtools doesn't show the source code but the hard to read minified code. 

Similar bugs: 
1. https://github.com/vitejs/vite/issues/5834 although this report mentions that  "the application does indeed break at the expected moment, and both Chrome Debugger and VSCode highlight the same (correct) lines", which is different behavior than mentioned in this report.

2. https://github.com/vitejs/vite-plugin-react/issues/23 might be the same issue but uses react. It does mention that a browser refresh fixes it, but does not mention the problem that setting breakpoints elsewhere in the code is no longer always possible.

The issue at hand seems that after HMR the sourcemaps get messed up. I suspect that the issue goes deeper than that as I have a more complex app where the source map remains incorrect even after clearing the cache. Anyway lets fix get the simple case addressed.

### Reproduction

1. Create a new vite app as follows
>  yarn create @vitejs/app; select vue as framework and vue-ts as the variant
2. Build and run the dev server:
>  yarn 
>  yarn dev
3. start vscode (I'm using 1.62.3) and add the project folder to the workspace
4. configure the launcher for chrome - run - add configuration - chrome; change the url port to 3000
5. Start debugging. This should launch chrome displaying the vite demo app
6. Open src/components/HelloWorld.vue in vscode and set a breakpoint on line 29, eg the button that has count++
7. Click on the button: -> result vscode stops at the breakpoint as expected
8. Edit the line to increment count by two, eg count+=2. Save
9. Click on the button again
Expected behavior: vscode stops at the breakpoint
Actual behavior: breakpoint is ignored

After reloading the browser (F5) the breakpoint works again in this simple example until the code changes.

To spice it up a bit, replace the line with count++ to invoke a function 'incrementCount as follows: 
```
  <button type="button" @click="() => incrementCount()">count is: {{ count }}</button>
```
and add this function in the script section:
```
const incrementCount = () => {
  count.value += 22
}
```

Repeat the test, this time setting the breakpoint in the function.-> this works as expected

Now try to set the breakpoint on the line with the button click. vscode will add a breakpoint in HelloWorld.vue?import=&t=1638336354075 (or something like it). 

Hit the count button again... => expected behavior, the debugger stops. Actual behavior: the debugger does not stop.
Hit F5 in the browser. => expected behavior, the browser refreshes and shows the app. Actual behavior, the debugger stops somewhere randomly.

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (4) x64 Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz
    Memory: 5.43 GB / 23.32 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Browsers:
    Chrome: 94.0.4606.61
    Firefox: 94.0
  npmPackages:
    @vitejs/plugin-vue: ^1.9.0 => 1.10.1 
    vite: ^2.5.10 => 2.6.14
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/vue-next instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by madsnedergaard** [comment] 2022-12-21 12:18
Not sure this should have been transferred to `vite-plugin-vue`, we're having the same problem with React! :(

**Comment by matija2209** [comment] 2023-01-10 11:30
> hmr: false

That worked for me. I'm using Vite 4.x and React with Typescript. Until that change, Vite was unusable for me. I was very close to switching. Thanks

**Comment by cryptoGF** [comment] 2023-01-12 04:46
similar problem here:

- I couldn't set breakpoint on some certain lines of code.
- sometimes the breakpoint is drifting to another line.
- you can set a breakpoint an en empty line.
- when breakpoint gets hit, the variable is undefined where it is in fact not.

**It seems all the above behaviors are due to the out of sync source maps**

**Comment by hspaay** [comment] 2023-01-12 17:05
@cryptoGF  Yes I think that Vite doesn't do HMR. Source maps are correct until a HMR takes place.

**Comment by baiej214** [comment] 2023-01-31 02:10
这问题一年过去了还没解决吗？

**Comment by tingshuai** [comment] 2023-02-19 00:49
我的项目也出现了相同问题；经过多次测试。发现使用了element-plus全局自动按需引入后会出现这个问题；具体是因为unplugin-vue-components、unplugin-auto-import这两个包。当安装了这两个包后发现node_modules里面会多出几个webpack相关的包；
卸载后断点正常；

**Comment by ys3322** [comment] 2023-02-20 01:55
上面老哥说的对，经测试把unplugin-xx自动导入的插件卸载，调试正常了

**Comment by Tobiaqs** [comment] 2023-03-14 20:44
I can't speak for everyone because my setup is slightly unusual, but I'm able to debug a Vue 3 SFC TS application in VSCode using the Firefox extension. Here is my raw config (note that my frontend project is a subfolder of the workspace folder).

My config is unusual because in development, a Django application serves a HTML which includes scripts from another virtual host, where Vite is running.

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "firefox",
            "request": "launch",
            "name": "vuejs: firefox",
            "url": "https://theproject.dev.somedomain.nl",
            "pathMappings": [
                {
                    "url": "file:///app", // /app is the path where my frontend project is mounted in a docker container running Vite
                    "path": "${workspaceFolder}/frontend"
                },
                {
                    "url": "https://frontend.theproject.dev.somedomain.nl/node_modules",
                    "path": "${workspaceFolder}/frontend/node_modules"
                }
            ],
            "profile": "default",
            "keepProfileChanges": true,
            "log": {
                "consoleLevel": {
                    "PathConversion": "Debug",
                    "default": "Error"
                },
            },
            "skipFiles": [
                "${workspaceFolder}/frontend/node_modules/**/*.js"
            ],
        }
    ]
}
```

This is what it should look like if I adjust the paths to those of a regular setup


```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "firefox",
            "request": "launch",
            "name": "vuejs: firefox",
            "url": "http://localhost:5173",
            "pathMappings": [
                {
                    "url": "file://${workspaceFolder}",
                    // "url": "file:///home/me/repos/myviteproject", // Alternatively...
                    "path": "${workspaceFolder}"
                },
                // Only mapping node_modules so we are able to ignore exceptions originating from there (see skipFiles)
                {
                    "url": "http://localhost:5173/node_modules",
                    "path": "${workspaceFolder}/node_modules"
                }
            ],
            "profile": "default",
            "keepProfileChanges": true, // Don't forget my cookies every time
            "log": {
                "consoleLevel": {
                    "PathConversion": "Debug", // Show debug messages about path mapping
                    "default": "Error"
                },
            },
            "skipFiles": [
                "${workspaceFolder}/node_modules/**/*.js" // Ignore node_modules exceptions
            ],
        }
    ]
}
```

**Comment by khaledOghli** [comment] 2023-03-27 05:45
This Fixes the issue to me 

First Try to set HMR to true
```
server: {
      hmr: true,
}
```
if this not fix the issue then try to set it as an object 
```
server: {
      hmr: {
        overlay: true,
        path: '/__hmr',
        protocol: 'ws',
        host: 'localhost',
        // port: 3333,
        // clientPort: 3333,
        timeout: 25000,
      },
}
```

**Comment by hspaay** [comment] 2023-03-30 17:34
@khaledOghli Thanks for the tip but I don't think this solves the issue.
Hmr works fine when enabled. The problem is that it updates the source maps get out of sync with the sources themselves. The result is that breakpoints end up on the wrong line.

@Tobiaqs interesting. I'm no longer using vue because of this issue, but maybe someone else can test this?

**Comment by itbeginshere** [comment] 2023-04-08 10:33
> I can't speak for everyone because my setup is slightly unusual, but I'm able to debug a Vue 3 SFC TS application in VSCode using the Firefox extension. Here is my raw config (note that my frontend project is a subfolder of the workspace folder).
> 
> My config is unusual because in development, a Django application serves a HTML which includes scripts from another virtual host, where Vite is running.
> 
> ```
> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "type": "firefox",
>             "request": "launch",
>             "name": "vuejs: firefox",
>             "url": "https://theproject.dev.somedomain.nl",
>             "pathMappings": [
>                 {
>                     "url": "file:///app", // /app is the path where my frontend project is mounted in a docker container running Vite
>                     "path": "${workspaceFolder}/frontend"
>                 },
>                 {
>                     "url": "https://frontend.theproject.dev.somedomain.nl/node_modules",
>                     "path": "${workspaceFolder}/frontend/node_modules"
>                 }
>             ],
>             "profile": "default",
>             "keepProfileChanges": true,
>             "log": {
>                 "consoleLevel": {
>                     "PathConversion": "Debug",
>                     "default": "Error"
>                 },
>             },
>             "skipFiles": [
>                 "${workspaceFolder}/frontend/node_modules/**/*.js"
>             ],
>         }
>     ]
> }
> ```
> 
> This is what it should look like if I adjust the paths to those of a regular setup
> 
> ```
> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "type": "firefox",
>             "request": "launch",
>             "name": "vuejs: firefox",
>             "url": "http://localhost:5173",
>             "pathMappings": [
>                 {
>                     "url": "file://${workspaceFolder}",
>                     // "url": "file:///home/me/repos/myviteproject", // Alternatively...
>                     "path": "${workspaceFolder}"
>                 },
>                 // Only mapping node_modules so we are able to ignore exceptions originating from there (see skipFiles)
>                 {
>                     "url": "http://localhost:5173/node_modules",
>                     "path": "${workspaceFolder}/node_modules"
>                 }
>             ],
>             "profile": "default",
>             "keepProfileChanges": true, // Don't forget my cookies every time
>             "log": {
>                 "consoleLevel": {
>                     "PathConversion": "Debug", // Show debug messages about path mapping
>                     "default": "Error"
>                 },
>             },
>             "skipFiles": [
>                 "${workspaceFolder}/node_modules/**/*.js" // Ignore node_modules exceptions
>             ],
>         }
>     ]
> }
> ```

Your solution worked for me! This issue has been racking my brain for a while now. I will be posting my config file too so that others may hopefully have some success too. I use React, Typescript and Vite. You are a star! 💪🐤💪

**Comment by itbeginshere** [comment] 2023-04-08 10:42
So I have been struggling with this issue for a while now. I am not too sure if this is in fact a vite issue, I think it is more along the lines of one's vs code launch files not being set up correctly. I am no expert in setting these up, it is the first time I have set up such a complex one. The solution I am working on uses React, Typescript and Vite. 

Below I show the setup of what works for me, it may not work for you, or perhaps you use a different framework/library, but be certain that all the file/folder/path mappings are pointing to the correct locations. In my case, I was missing the `pathMapping` field. Looking over the example provided by @Tobiaqs I was able to see what I was missing. 

@hspaay It worked for me.


The `preLaunchTask` can be ignored here.
```
// launch.json
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "chrome",
        "request": "launch",
        "skipFiles": ["${workspaceFolder}/node_modules/**/*.js"],
        "name": "Chrome (DEV)",
        "sourceMaps": true,
        "preLaunchTask": "NPM START",
        "url": "http://127.0.0.1:8080/",
        "webRoot": "${workspaceFolder}/src",
        "sourceMapPathOverrides": {
          "webRoot": "${workspaceRoot}/src"
        },
        "pathMapping": {
          "url": "file://${workspaceFolder}/src",
          "path": "${workspaceFolder}/src",
        }
      },
    ]
  }
```

```
// vite.confi.js
/* eslint-disable no-undef */
import * as path from 'path';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import eslint from 'vite-plugin-eslint';

export default defineConfig({
    root: 'src', 
    build: {
        outDir: '../dist',
        sourcemap: true,
        emptyOutDir: true, 
    },
    css: {
        devSourcemap: true,
    },
    publicDir: '../assets',
    plugins: [
        react({
            include: '**/*.{jsx,tsx,ts,js}',
        }),
        eslint(),
    ],
    server: {
        port: 8080,
        strictPort: true,
    },
    resolve: {
        alias: {
            src: path.resolve(__dirname, 'src'),
        }
    }
});
```

**Comment by perintery** [comment] 2023-04-13 02:38
> 我的项目也出现了相同问题；经过多次测试。发现使用了element-plus全局自动按需引入后会出现这个问题；具体是因为unplugin-vue-components、unplugin-auto-import这两个包。当安装了这两个包后发现node_modules里面会多出几个webpack相关的包； 卸载后断点正常；

正常指, 可以在chrome中断点了?

**Comment by perintery** [comment] 2023-04-13 02:43
我说一下自己的分析: 我使用的vite+react+ts的项目
1. 项目跑起来来后, 在chrome的source文件里面看到的其实就是编译后的js代码, 我们在里面断点时候, 断点就打在这个文件上面
2. 当我们更新源文件的时候, 触发hmr流程, 最后会加载一个新的编译好的js文件, 我们打断点的那个文件, 已经不会被执行到了.

所以要接这个问题, 就是怎么把old文件上的断点信息,带到新的文件上面来.
------------------------------
I'll give my own analysis: I'm using a project with vite+react+ts.

After running the project, what we see in the source files in Chrome is actually the compiled JS code. When we set a breakpoint in it, it is set on this file.
When we update the source file, it triggers the HMR process and finally loads a new compiled JS file. The file where we set the breakpoint will not be executed anymore.
So the question is how to transfer the breakpoint information from the old file to the new file?

------------
how?

**Comment by yyx990803** [comment] 2023-04-25 09:28
To clarify debugging is currently working fine with Chrome Devtools' debugging for the following cases:

1. `debugger` statements in source code, e.g. `@click="debugger; count++"`
2. Breakpoints attached via Chrome Devtools' Source panel.

It only breaks after HMR if the debugging is done by launching via VSCode. **So the solution is to prefer Chrome's native debugger instead of VSCode's debugger.** You'll also find that Chrome's native debugger is more reliable and much faster.

As for the VSCode issue, it is not really caused by Vue or plugin-vue, but an incompatibility between VSCode's debugger and how Vite HMR works. I'm not sure if this is something we can fix - if anything, this seems to be something VSCode should be fixing since Vite is working fine with Chrome's native debugger as far as I can tell.

**Closed by yyx990803** 2023-04-25 09:28 UTC
Labels: pending triage

**Comment by hspaay** [comment] 2023-04-26 01:24
Hmm, not saying you're wrong, but this is a bit of a stretch. Saying that 'since it works in chrome it can't be vite' has a few shortcomings.

1. This is just an assumption. Without understanding the root cause this statement is unfounded.
2. The problem exists for both VSCode and Jetbrains Intellij. Are both tools to blame for not handling typescript/HMR properly? 

I think it is incorrect to close this issue as nothing has been resolved.

**Comment by rotu** [comment] 2023-05-07 05:28
I encountered this too, and I think the issue is "content validation" in the `vscode-js-debug` extension. I think I found that adding `"enableContentValidation": false` in my launch configuration fixes this issue.

```json
// file: launch.json
{
   "version": "0.2.0",
   "configurations": [
      {
         "type": "chrome",
         "request": "launch",
         "name": "Chrome",
         "url": "http://localhost:8080",
         "enableContentValidation": false
      }
   ]
}
```

Here's what the documentation for `enableContentValidation` says:

> Toggles whether we verify the contents of files on disk match the ones loaded in the runtime. This is useful in a variety of scenarios and required in some, but can cause issues if you have server-side transformation of scripts, for example.

https://github.com/microsoft/vscode-js-debug/blob/8afb1e8c421a3bef2b0e264bc9e00f7b4922b02c/src/adapter/threads.ts#L1479
