### ISSUE TITLE
HMR is not working when including component from some npm package

### ISSUE THREAD

**Issue by tchiotludo** [vitejs/vite-plugin-vue#58] opened 2022-12-13 20:40 UTC
### Describe the bug

I use `vue-material-design-icons` on vue-cli project without any issues. I try to move to vite and all is working except this package, can't figure why. 

- When I include an icon from the lib (uncomment line 3 from HelloWorld.vue), the HMR is not working
- I see on the network tab the right, that the module is properly loaded, but not refresh on the page
- With a full refresh (f5), I can see the modification. 

I've try to include exactly the same component on Local (`Local.vue`) and the HMR is working fine. 

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ryvwef?file=src%2Fcomponents%2FHelloWorld.vue&terminal=dev

### Steps to reproduce

- uncomment line 3 from HelloWorld.vue
- See the HMR that is not working anymore

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
    vite: ^4.0.0 => 4.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment] 2023-01-05 07:59
Adding `optimizeDeps.exclude = ['vue']` to `vite.config.js` seems to work.
```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  optimizeDeps: {
    exclude: ['vue']
  }
})
```

Because `vue-material-design-icons` imports `vue` inside a vue file and `vue` is optimized, this is a duplicate of https://github.com/vitejs/vite/issues/3910.

**Closed by sapphi-red** 2023-01-05 07:59 UTC
Labels: pending triage
