### ISSUE TITLE
Vite picking up styles only for root component

### ISSUE THREAD

**Issue by cawa-93** [vitejs/vite-plugin-vue#201] opened 2023-07-12 17:40 UTC
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

I create a custom element inside which I wrap a multi-components vue application. For some reason, vite ignores the styles of nested components and only inserts the styles of the root component.

In reproduction, expected two lines of text: one red and one green. Actual: two lines of text: one red and one black;

### Reproduction

https://stackblitz.com/edit/vitejs-vite-djrzdx?file=src%2FApp.ce.vue

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.3 - /usr/local/bin/pnpm
  npmPackages:
    @vitejs/plugin-vue: ^4.2.3 => 4.2.3 
    vite: ^4.4.2 => 4.4.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by IP-Developer** [comment] 2023-11-30 08:44
Bump! Can confirm the same happens in our app.

**Comment by edison1105** [comment] 2024-09-30 07:09
duplicate of https://github.com/vuejs/core/issues/4662
fixed via https://github.com/vuejs/core/pull/11517

**Closed by edison1105** 2024-09-30 07:09 UTC
Labels: bug
