### ISSUE TITLE
get wrong cached file when i run vite build in watch mode

### ISSUE THREAD

**Issue by SBDavid** [vitejs/vite-plugin-vue#228] opened 2023-08-13 04:47 UTC
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

**What I'm doing:** Using the Vite build API to build a Vue project using watch mode.

**My expected outcome:** The content within <script lang='ts'> should update correctly when I save.

**Actual result:** The content within <script lang='ts'> always hit wrong cached file.

when i commot out cache in src/utils/descriptorCache.ts，i can build successfully.

line: 47 in src/utils/descriptorCache.ts
```js
export function getDescriptor(
  filename: string,
  options: ResolvedOptions,
  createIfNotFound = true,
): SFCDescriptor | undefined {
  // if (cache.has(filename)) {
  //   return cache.get(filename)!
  // }
  if (createIfNotFound) {
    const { descriptor, errors } = createDescriptor(
      filename,
      fs.readFileSync(filename, 'utf-8'),
      options,
    )
    if (errors.length) {
      throw errors[0]
    }
    return descriptor
  }
}
```

### Reproduction

https://github.com/SBDavid/vite-build-demo

### 1. my config file

```js
import { defineConfig } from 'vite'
import viteCommonjs from 'vite-plugin-commonjs'
import vue from '@vitejs/plugin-vue'
import nodeResolve from '@rollup/plugin-node-resolve'

export default defineConfig({
  mode: 'development',
  root: './',
  plugins: [
    vue(),
    viteCommonjs()
  ],
  build: {
    lib: {
      entry: './src/index.vue',
      name: 'skt-slide-show',
      fileName: 'index',
      formats: ['umd'],
      emitAssets: true,
    },
    emptyOutDir: true,
    assetsInlineLimit: 0,
    target: ['chrome67'],
    minify: false,
    sourcemap: false,
    outDir: 'dist',
    rollupOptions: {
      external: ['vue'],
      plugins: [
        nodeResolve({
          extensions: ['.mjs', '.js', '.json', '.vue', '.ts']
        }),
      ],
      output: {
        globals: {
          vue: "__Vue__"
        },
      },
    }
  }
})
```

### 3. start build from cmd

`npm run dev`

```json
"scripts": {
    "dev": "vite build --watch --config ./vite.config.js"
  },
```

### 4. my vue entry file
```js
<script lang='js'>
import fff from './mod'
export default {
    fff
}
</script>
```

### 5. udpate entry to emit a error, for example
```js
<script lang='js'>
import fff from './mod1' // import a non exist file
export default {
    fff
}
</script>
```

Then I can get a error as expected:
Could not resolve "./mod1" from "src/mobile/index.vue?vue&type=script&lang.js"

### 6. revert the entry file, and save

What is expected is compile should success, but I still get the save error.

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 71.59 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    pnpm: 8.6.12 - ~/.nvm/versions/node/v16.17.0/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.5
  npmPackages:
    @vitejs/plugin-vue: 4.2.3 => 4.2.3 
    @vitejs/plugin-vue-jsx: ^3.0.1 => 3.0.1 
    rollup: ^3.27.1 => 3.28.0 
    vite: 4.4.8 => 4.4.8
```

### Used Package Manager

npm

### Logs

build started...
✓ 3 modules transformed.
dist/index.umd.js 0.43 kB │ gzip: 0.25 kB
built in 201ms.

build started...
✓ 2 modules transformed.
Could not resolve "./mod1" from "src/index.vue?vue&type=script&lang.js"
file: /XXX/vite-build-demo/src/index.vue?vue&type=script&lang.js

build started...
✓ 1 modules transformed.
Could not resolve "./mod1" from "src/index.vue?vue&type=script&lang.js"
file: /XXX/vite-build-demo/src/index.vue?vue&type=script&lang.js

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by edison1105** [comment] 2024-09-24 06:18
Closing as it can't reproduce with
```json
    "@vitejs/plugin-vue": "5.1.4",
    "vite": "5.4.7",
```

**Closed by edison1105** 2024-09-24 06:18 UTC
Labels: cannot reproduce
