### ISSUE TITLE
No component in build version

### ISSUE THREAD

**Issue by psqq** [vitejs/vite-plugin-vue#265] opened 2023-10-12 07:44 UTC
### Describe the bug

One component ceases to exist in the production build created via `vite build`. I hope I correctly identified that this is a `vite` bug. When I use `npm run dev` the component is shown.

When this component is explicitly exported and added to `components: { ... }` it starts working everywhere. It turns out that `vite build` for some reason excludes it from the build.

I created a repository that reproduces this error: https://github.com/psqq/vite-no-form

### Reproduction

https://github.com/psqq/vite-no-form

### Steps to reproduce

Steps:

```bash
cd ~/tmp
npm create vite@latest
```

```
✔ Project name: … json-forms
✔ Select a framework: › Vue
✔ Select a variant: › TypeScript
```

```bash
cd ~/tmp/json-forms
npm install
npm i --save @jsonforms/core @jsonforms/vue @jsonforms/vue-vanilla
```

Change source code: https://github.com/psqq/vite-no-form/commit/a0fd4d94fecb9ce71dfeacb36a679dcac2244d73

# dev

If you run `npm run dev` the form is displayed

# build

If you run it:

```bash
npm run build
npx http-server -c-1 dist
```

If you uncomment JsonForm2 in App.vue, both forms will be displayed after assembly.

### System Info

```shell
System:
    OS: Linux 6.4 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 1800X Eight-Core Processor
    Memory: 20.51 GB / 31.27 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^4.2.3 => 4.4.0 
    vite: ^4.4.5 => 4.4.11
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment] 2023-10-12 14:15
Duplicate of #11

**Closed by sapphi-red** 2023-10-12 14:15 UTC
Labels: pending triage
