### ISSUE TITLE
defineProps导致热更新失效

### ISSUE THREAD

**Issue by thikiiii** [vitejs/vite-plugin-vue#374] opened 2024-03-20 07:16 UTC
### Describe the bug

我使用 defineProps<Test>(),会导致当前组件热更新失败

### Reproduction

https://stackblitz.com/edit/vitejs-vite-rckp9s?file=package.json,src%2FApp.vue,src%2Ftype.ts&terminal=dev

### Steps to reproduce

当 defineProps 使用泛型的时候，你在当前组件的任何操作都会导致热更新失败，必须的重启项目，去掉泛型一切都正常

### System Info

```shell
"dependencies": {
    "vue": "^3.4.21",
    "ant-design-vue": "^4.1.2"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.4",
    "typescript": "^5.2.2",
    "vite": "^5.1.6",
    "vue-tsc": "^2.0.6"
  }
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by edison1105** [comment] 2024-09-16 08:50
duplicate of https://github.com/vitejs/vite-plugin-vue/issues/428

**Closed** 2024-09-16 09:06 UTC
Labels: pending triage
