### ISSUE TITLE
HMR with an external script does not proper reload

### ISSUE THREAD

**Issue by cub** [vitejs/vite-plugin-vue#8] opened 2022-03-15 09:47 UTC
### Describe the bug

I have a problem with HMR with Vue. When I modify my external script, HMR reload the .vue but stay in an old state.
```html
<!-- test-hmr.vue -->
<template>
  <div class="test-hmr">
    TestHmr !
    {{ qqq }}
  </div>
</template>
<script lang="ts" src="./test-hmr.ts"></script>
```
```ts
// test-hmr.ts
import { defineComponent } from 'vue';
export default defineComponent({
  name: 'TestHmr',
  data() { return { /* qqq:'weeeeeeee' */ }; }
});
```
I see in the console the warning `[Vue warn]: Property "qqq" was accessed during render but is not defined on instance.`, it's normal.
Then I uncomment `qqq:'weeeeeeee'` and save the .ts.
I see in the console `[vite] hot updated: /src/components/test-hmr/test-hmr.vue`.
But the render is not showing the `weeeeeeee`, it's stuck with the not defined previous state.

On the very first load, it reload/refresh nicely. If you rename the `qqq` to something else in the .vue, save, then edit accordingly the .ts, it will stuck in previous state.

Note, if I insert the content of my .ts inside the `<script>`, the HMR works well.
The problem only occurs with external script file.

### Reproduction

https://github.com/cub/test-hmr

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 8.83 GB / 15.50 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/bin/node
    npm: 8.5.4 - /usr/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Chromium: 99.0.4844.51
    Firefox: 98.0.1
  npmPackages:
    @vitejs/plugin-vue: ^2.2.4 => 2.2.4 
    vite: ^2.8.6 => 2.8.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cub** [comment] 2022-12-16 09:26
Still happen with `vite 4.0.1` and `@vitejs/plugin-vue 4.0.0` (latest version at this time).

**Comment by tehomen** [comment] 2023-11-16 18:30
This issue is still happening. When you first start vite, you'll be able to change content in ts file and it will update, but after making a change to anything within the vue template if you change anything within the ts file that the template references vite says it updated but no updates are actually made to the page.

**Comment by edison1105** [comment] 2024-11-09 12:34
It seems a duplicate of #7. please try these [pre-releases](https://github.com/vitejs/vite-plugin-vue/pull/471#issuecomment-2464913460 ) packages.

**Closed** 2024-11-11 01:10 UTC
Labels: bug, feat: hmr, p3-minor-bug :hammer:
