### ISSUE TITLE
with `verbatimModuleSyntax: true` type only imports don't work in dev mode

### ISSUE THREAD

**Issue by stefanprobst** [vitejs/vite-plugin-vue#253] opened 2023-09-13 14:17 UTC
### Describe the bug

with `"verbatimModuleSyntax": true` in `tsconfig.json` i get the following errors when using type imports from a type-only package (`@types/geojson`):

```
[plugin:vite:import-analysis] Failed to resolve import "geojson" from "pages/index.vue". Does the file exist?
```
![error-message](https://github.com/vitejs/vite/assets/20753323/6fc05558-38a1-403a-af1c-40b8b5735b4e)

---

setting `"verbatimModuleSyntax": false` makes everything render fine.

also, this is only an issue in development, not in a production build.

### Reproduction

https://github.com/stefanprobst/issue-vite-type-imports

### Steps to reproduce

- `npm install`
- `npm run dev`
- open http://localhost:3000

### System Info

```shell
System:
    OS: Linux 6.4 KDE neon 5.27 5.27
    CPU: (16) x64 AMD Ryzen 7 5800U with Radeon Graphics
    Memory: 23.20 GB / 30.66 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.1 - ~/.volta/tools/image/node/18.17.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.6.7 - ~/.volta/tools/image/node/18.17.1/bin/npm
    pnpm: 8.7.4 - ~/.volta/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Firefox Nightly: 119.0a1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment] 2023-09-14 07:12
Might be related to #24

**Comment by stefanprobst** [comment] 2023-09-14 08:05
> The error is expected because verbatimModuleSyntax: true will make import {  type Polygon } from 'geojson' to be transpiled to import {} from 'geojson'.

not sure i understand, are you saying that `import { type Point } from 'geojson'` is invalid syntax with `verbatimModuleSyntax` and is expected to throw?

**Comment by sapphi-red** [comment] 2023-09-14 11:00
It's a valid syntax. But the "unable to resolve" error should happen.

`import { type Point } from 'geojson'` will be transpiled to `import {} from 'geojson'` (equivalent to `import 'geojson'`). So `geojson` will be preserved in the output. If you use `import type { Point } from 'geojson'` then that import will be removed when transpiled.
https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax:~:text=The%20type%20modifier%20on%20imports%20and%20exports%20helps%20with%20these%20situations%20a%20bit.%20We%20can%20make%20it%20explicit%20whether%20an%20import%20or%20export%20is%20only%20being%20used%20for%20type%20analysis%2C%20and%20can%20be%20dropped%20entirely%20in%20JavaScript%20files%20by%20using%20the%20type%20modifier.

But if `verbatimModuleSyntax` is `false`, TypeScript will remove that import unless the imported value is used as a value.

**Comment by stefanprobst** [comment] 2023-09-14 11:53
ah TIL, thanks for explaining!

in case it's useful for others: when enforcing inline type imports with eslint, also enable [`no-import-type-side-effects`](https://typescript-eslint.io/rules/no-import-type-side-effects):

```json
"@typescript-eslint/consistent-type-imports": ["error", { "fixStyle": "inline-type-imports" }],
"@typescript-eslint/no-import-type-side-effects": "error",
```

**Comment by sapphi-red** [comment] 2023-10-09 18:16
> But in a vue file, it doesn't throw an error in build. That's a bug. I guess it's somehow not respecting the tsconfig.json.

Taking a second look, it does throw an error in build as well.
https://stackblitz.com/edit/vitejs-vite-eyjdj5?file=tsconfig.json,src%2Fcomponents%2FHelloWorld.vue&terminal=build
Closing as it's working as intended.

**Closed by sapphi-red** 2023-10-09 18:16 UTC
Labels: p3-minor-bug :hammer:
