### ISSUE TITLE
Vite HMR bug when text child no wrap tag

### ISSUE THREAD

**Issue by lxfljw** [vitejs/vite-plugin-vue#285] opened 2023-11-06 06:41 UTC
### Describe the bug

When I modify the text in div  like this：
  ```html
  <div>
    this is some text
    <img src='xxx' /> 
  </div>
  ```
and vite hmr show me an error in Console:
【Cannot set properties of null (setting 'nodeValue') in the function `setText`】the vnode's el is null，
When modify the text to wrap by a  tag like this and  hmr work normally：

  ```html
  <div>
    <span> this is some text</span>
    <img src='xxx' />
  </div>
  ```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-3aqfqb?file=_gitignore,main.js,App.vue,vite.config.ts&terminal=dev

### Steps to reproduce

```shell
npm i
npm run dev
```
change file `App.vue` some text 

hmr show Cannot set properties of null (setting 'nodeValue') in the function `setText`，

### System Info

```shell
System:
    OS: Windows 11 10.0.22000
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 2.60 GB / 15.87 GB
  Binaries:
    Node: 14.21.3 - E:\nvmlink\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.15 - E:\nodejs\npm.CMD
    pnpm: 7.9.5 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Chrome: 119.0.6045.105
    Edge: Spartan (44.22000.120.0), Chromium (119.0.2151.44), ChromiumDev (Active code page: 65001)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-vue: ^4.4.0 => 4.4.0
    vite: ^4.5.0 => 4.5.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by brc-dd** [comment] 2023-11-25 08:05
Seems to be working fine now with latest version of deps.

**Comment by yyx990803** [comment] 2023-12-26 02:39
Closing as cannot reproduce

**Closed by yyx990803** 2023-12-26 02:39 UTC
Labels: pending triage
