### ISSUE TITLE
HMR infinite loop inside `deepEqual`

### ISSUE THREAD

**Issue by aguingand** [vitejs/vite-plugin-vue#400] opened 2024-05-06 06:40 UTC
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

I can reproduce an infinite loop during HMR. I have located the loop inside [`deepEqual`](https://github.com/vitejs/vite-plugin-vue/blob/46d0baa45c9e7cf4cd3ed773af5ba9f2a503b446/packages/plugin-vue/src/handleHotUpdate.ts#L205) function introduced in (#258 and #334). It seems to appear when importing third-party library (here radix-vue / vue) because it recursively walk through the AST of the library components / TS definitions (non-project file).

Related issue #350.

### Reproduction

https://stackblitz.com/edit/vite-plugin-vue-hmr-inifite-loop-repro

### Steps to reproduce

- Edit `src/App.vue` HMR works
- Edit `src/components/ui/alert-dialog/AlertDialog.vue` HMR hangs

### System Info

```shell
System:
    OS: macOS 12.7.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 1.88 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 8.15.8 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
  npmPackages:
    @vitejs/plugin-vue: ^5.0.4 => 5.0.4
    vite: ^5.2.11 => 5.2.11
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aguingand** [comment] 2024-05-06 16:13
I've updated system infos, it occurs in latest version (`5.0.4`). Version `4.6.2` is not affected.

**Comment by elliots** [comment] 2024-05-12 01:17
I'm seeing this in our project too 
![image](https://github.com/vitejs/vite-plugin-vue/assets/622455/81094aa3-4d7d-456f-aeb5-e5560ce6b4f6)

**Comment by edison1105** [comment] 2024-09-16 08:51
duplicate of https://github.com/vitejs/vite-plugin-vue/issues/428

**Closed** 2024-09-16 09:06 UTC
Labels: p3-significant 🔨
