### ISSUE TITLE
SyntaxError: Identifier '$' has already been declared

### ISSUE THREAD

**Issue by zz541843** [vitejs/vite-plugin-vue#60] opened 2022-12-13 08:25 UTC
### Describe the bug

I am creating a component library using the following configuration
```js
export default defineConfig({
    plugins:[
        vue({
            reactivityTransform: true
        }),
    ], 
    ...
})
```
After compiling, this module is introduced in a new project and reactivityTransform is also turned on
This error occurs. I tried vitejs/vite#7854, but it didn't work
[https://github.com/vitejs/vite/issues/7854](url)

### Reproduction
https://stackblitz.com/edit/vitejs-vite-t4zpxn?file=src%2Fcomponents%2FHelloWorld.vue&terminal=dev

### System Info

```shell
"vue": "^3.2.45",
"@vitejs/plugin-vue": "^3.2.0",
"vite": "^3.2.5"
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment] 2022-12-15 07:53
I created a repro.
https://stackblitz.com/edit/vitejs-vite-t4zpxn?file=src%2Fcomponents%2FHelloWorld.vue&terminal=dev
I guess this is a bug in @vue/reactivity-transform.

**Comment by sxzz** [comment] 2023-01-11 09:48
I don't think it's a bug of vue core. `$('foo')` is not a valid syntax of Reactivity Transform. We should use `const foo = $('foo')` instead.

Also if we want to exclude this file, just configure it with a RegExp for the `reactivityTransform` option.

@sapphi-red

**Comment by LinusBorg** [comment] 2023-01-11 10:18
I think the specific issue the OP supposedly has, is that 

* they have a 3rd party dependency in `node_modules` that uses `$()` in its code, unrelated to ReactivityTransform (likely jQuery)
* but plugin-vue still tries to apply the transform
* even though in the plugin's README, we state:

> `true`: transform will be enabled for all vue,js(x),ts(x) files except
>              those inside node_modules

**Comment by sapphi-red** [comment] 2023-01-11 11:35
@sxzz @LinusBorg 

> It's documented that ReactivityTransform will transform $() in any projects files.
> https://github.com/vuejs/core/issues/7501#issuecomment-1378341814

Oh, I didn't know about this. I searched the documentation but I overlooked it.

> And though plugin does exclude node_modules content for non-"normal" file types, there's a loop hole:

In this case, the library code is linked (`workspace:*`, symlink) and is not treated as in `node_modules`.
Vite dereferences the file path to symlinks so plugins aren't possible to tell whether the original file path is in `node_modules` or not.
So I guess `reactivityTransform` needs to be set in this case.

> I _think_ the specific issue the OP supposedly has, is that
> 
> * they have a 3rd party dependency in `node_modules` that uses `$()` in its code, unrelated to ReactivityTransform (likely jQuery)
> * but plugin-vue still tries to apply the transform

This is the more accurate reproduction of original issue: https://stackblitz.com/edit/vitejs-vite-7lr4hh?file=src%2Fcomponents%2Ffoo.js&terminal=dev
(I over simplified the previous repro because I was thinking reactivity transform doesn't apply to non-vue files.)

The library includes a code like this:
```js
function $() {}
function f() {}
export { f as foo }
```
Function names are mangled by minifier. 
So if this file is imported, reactivity transform tries to transform this file and fails with `$ can only be used as the initializer of a variable declaration.`.
Is this one expected? In other words, does it disallow users to have a variable named `$`?

If this is expected, I think we can close this issue as working as intended.

**Comment by sxzz** [comment] 2023-01-11 14:32
I checked out his reproduction repo, and I think it's because of path of link, as @sapphi-red mentioned.
> In this case, the library code is linked (workspace:*, symlink) and is not treated as in node_modules.

Also, maybe the plugin should convert `true` to `projectPath` by default.

https://github.com/vitejs/vite-plugin-vue/blob/8f4a5dc466474d6974195b44fd1a9a7275e2f4b9/packages/plugin-vue/src/index.ts#L102

```diff
--- ? createFilter(/\.(j|t)sx?$/, /node_modules/) 
+++ ? createFilter([projectPath, /\.(j|t)sx?$/], /node_modules/) 
```

---

For his reproduction, here is the solution:

```
--- a/packages/xx-web/vite.config.ts
+++ b/packages/xx-web/vite.config.ts
@@ -1,5 +1,5 @@
 import {fileURLToPath, URL} from "node:url";
-
+import {resolve} from 'path'
 import {defineConfig} from "vite";
 import vue from "@vitejs/plugin-vue";
 import vueJsx from "@vitejs/plugin-vue-jsx";
@@ -7,7 +7,7 @@ import vueJsx from "@vitejs/plugin-vue-jsx";
 // https://vitejs.dev/config/
 export default defineConfig({
     plugins: [vue({
-        reactivityTransform: true
+        reactivityTransform: resolve(__dirname, 'src')
     }), vueJsx()],
     resolve: {
         alias: {
```

**Closed** 2023-02-10 17:35 UTC
Labels: pending triage

**Comment by sxzz** [comment] 2023-02-10 17:40
Since Reactivity Transform has been deprecated, so we close the issue.

If you wanna continue to use it, you can refer to Vue Macros
