### ISSUE TITLE
在setup内使用slots 进行编辑 会导致vite热更新失败

### ISSUE THREAD

**Issue by foreinbug** [vitejs/vite-plugin-vue#128] opened 2023-03-10 00:53 UTC
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

使用useSlots 或者 setup(_, { slots }) 对插槽的内容进行操作的时候 会导致使用该插槽的组件热更新时发生错误 在vue sfc playround则没有问题 vite终端也并未出现编译错误 如果对页面进行刷新 能够正常看到修改的内容

### Reproduction

https://sfc.vuejs.org/#eNp1VW1vmzAQ/isnNAkiNbC+rJMYybp1H6dpWvqtVCoFh9CBbdkma5Xw33c2xAFCjAT2+e65515sds43zv1tTZzQiWQqCq5AElVzKBOaL2JHydhZxrSoOBMKVjxJCawFq8D1A7PSxu6XmMY0CloAVMeFIhUvE0VwBRAZVTONVZQVW62j2ufy6hrM0LuoGrTbZn6cAtx8uh1rRC0FnEeB9edcOC3beZVw/1UyirHtjOtuA0MKwUi0DPnrdexslOIyDIKa8r+5n7IquMO9QNRUFRWZZ6y6u/av/JvP6F+qvtwnspq/CPZPEoEeY+eiBx6gcEvEXBCaEUHE0JlcpzqDr9JnIh+rnuBq2CamDcZok9+r3GTNTKAYDa8VyQyx+9Xqt2CcCFUQaSQZWReU3KMSo4QqI9uYt1Z8eOfELGoqyBpnTdcCtvTkzbhCmKQuzbcP5xkKNKlICK7h7Ro4jtjSViKvlSLCLgEUug3hV129ENEl1DDVLkK4vO1kTffNCkFSVTB6ArFSoqA5JNJGE7mYVBf24KasrCvqLk8dGJWBj/ZtjodnuF/ADmTJlIRmdnCaMioVFNiOK/VeEljY3EeDvC89bwaL5ZFra5ijgcH223xAAFeY4lalWEPr2LfBwmKxaKlaBnoIJCloX4LpTrIM8/DAeAjPH59txL2970wpVp3d/knWmJjnD7u84W+TGn+KfDOt0tgosIHPkRxQPMUYszyr0REdRDFi2Ns7UGtm3aQjNlkgXW+skSm73zXLVx9V93t4fLJBdhAb70jAxWvr0FB6DIqTlonEs+Bu5/J4QDp6vflj36YPPuXgxIkeUndl74gcx7okbz+Oh2jUaCPcIa2ptc6Qj1ew51GWkWEqR206DuRcMJMB9YIy95Nnz95swnzM0iRVE3wayw/NYC1n/XUf25oeTNqG0q5MSw1/jIYryBQvggwlfldxWOINtm3Dw/8L/sveQ1MSBMATgxjaDg2c5j+E2EQb

### System Info

```shell
"vue": "^3.2.45"
 "@vitejs/plugin-vue": "^4.0.0",
 "vite": "^4.1.0",
 "vue-tsc": "^1.0.24"
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment] 2023-03-10 07:00
I wasn't able to reproduce. Would you write a more detailed steps?
https://stackblitz.com/edit/vitejs-vite-34enjy?file=src%2FSpace.vue,src%2FApp.vue&terminal=dev

**Comment by foreinbug** [comment] 2023-03-10 07:49
> 我无法复制。你会写一个更详细的步骤吗？ https://stackblitz.com/edit/vitejs-vite-34enjy?file=src%2FSpace.vue,src%2FApp.vue&terminal=dev

https://sfc.vuejs.org/#eNp1VV1vmzAU/StXaBKp1MD6sU5iJOvW12malj7yUAqGuAXbsk3WKOO/99oGF5KWSGBf33vOuR+QQ/BDiGjXkSAJUlVIKjQoojsBTc7qVRZolQXrjNFWcKlhI/KCQCV5C2EU250JDr9lLGNp7ADQHTeatKLJNcEdQGpd7TLTaUl3xke738XlFYDCC/AyHugeOxe7flsCXH+5OfZInQxcp7HnDM4Dp3jZ5iJ6UpxhfgdLPxxgWglYi7FhDmafBVuthUriuGPiuY4K3sa3eBbLjmnakmXJ29ur6DK6/or8Sk/tEVHt8lHyf4pIZMyC8wl4jMYdkUtJWEkkkXMyVRWmik8q4rI+dj3BNbB9xnrM0TfAdG9ecCwPFE2uFPZwt1TG0TZyLCnslhWXeEgxDiiDYkubEkmzAJJnsh9OIpa3GAiJ0vuGDMaNWXs0xMM6Cc4I05BQQ2icMCge+SbNcqtJq+ywDJP37szZJhmGTpPSFvVus/kjuSBSU6KspSQVZeRulGFtW3s3jvd7QeymY5JUuOqHEfajS14sFcLkXWOfU7iFlWAqkUBoax5aOIHYyk9R3WlNpN8CaKRN4HfXPhI5DINVaigSuLgZbP3wLKkkhaacnUBstKSshlz5bNIQByKE/xAWvOlaFq5PCazLjMPd7eu9sNrP4QCq4VpBfzaSFpwpDb7NsPK1T2d1Xy8WZ7Bav2l1gTUGWOzI1QNiuMQSOxdagSOOfLKwWq2cVK/AXBJFSja1YLnzssQ63HORwMPnB5/x5Own15q3Hx7/IhUW5uHToe7Fy7sef2m9fd+l91ngy/eRyJnEU4xjlR96DEJnWRwpnJyN0vqzYeFaMb7RkxYe92zIwM5ANEzO92gx4njA40xHaC/Bz8s4cDbQDJzFmP812G8JqAJHqURLNHyfYI3vwM6R4NcVPw/7BKqGvCAA1hwxTBwGBP0ro2Ql3w==

**Comment by foreinbug** [comment] 2023-03-10 07:52
> 我无法复制。你会写一个更详细的步骤吗？ https://stackblitz.com/edit/vitejs-vite-34enjy?file=src%2FSpace.vue,src%2FApp.vue&terminal=dev

虽然不知道为啥使用 h 函数在这个上面好使 但是这样写就不行了 我不清楚是否是我写的有问题 但是这样在SFC Playground上是好使的

**Comment by sapphi-red** [comment] 2023-03-10 13:11
OK. I reproduced it.

This is a duplicate of https://github.com/vitejs/vite-plugin-vue/issues/3.

**Closed by sapphi-red** 2023-03-10 13:11 UTC
Labels: pending triage
