### ISSUE TITLE
mjs file import type issue

### ISSUE THREAD

**Issue by xiaoxiangmoe** [vitejs/vite-plugin-vue#137] opened 2023-03-28 10:29 UTC
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [X] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

we can't use default import in mts file

### Reproduction

https://github.com/xiaoxiangmoe/vite-plugin-vue-mjs-bug.git

### Steps to reproduce

* yarn install
* yarn build

see error

```
$ tsc
src/test-mjs.mts:4:1 - error TS2349: This expression is not callable.
  Type 'typeof import("/Users/me/vite-plugin-vue-mjs-bug/node_modules/@vitejs/plugin-vue/dist/index")' has no call signatures.

4 vue({})
  ~~~

src/test-mjs.mts:5:1 - error TS2349: This expression is not callable.
  Type 'typeof import("/Users/me/vite-plugin-vue-mjs-bug/node_modules/@vitejs/plugin-vue-jsx/dist/index")' has no call signatures.

5 vueJsx({})
  ~~~~~~
```

### System Info

```shell
npmPackages:
    @vitejs/plugin-vue: ^4.1.0 => 4.1.0 
    @vitejs/plugin-vue-jsx: ^3.0.1 => 3.0.1 
    vite: ^4.2.1 => 4.2.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment] 2023-03-30 16:09
Duplicate of #48

**Closed by sapphi-red** 2023-03-30 16:09 UTC
Labels: pending triage
