### ISSUE TITLE
Can't run vue 3.3 project when generic is used

### ISSUE THREAD

**Issue by jd-solanki** [vitejs/vite-plugin-vue#162] opened 2023-04-30 10:48 UTC
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

When I run the project using `nr dev` with the latest deps and vue 3.3 I get the error: `Unexpected "="`

<details>
<summary>console image</summary>

![image](https://user-images.githubusercontent.com/47495003/235348864-b01b9538-6a7d-4806-b3f9-cf0335f969d8.png)

</details>

### Reproduction

https://github.com/jd-solanki/volar-vue-playground/tree/props-generics

### Steps to reproduce

> **Note**
> Make sure you are in `props-generics` branch

1. Clone the repo
2. go to `props-generics` branch
3. run `ni && nr dev`

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 8.36 GB / 15.95 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.64)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-vue: ^4.2.1 => 4.2.1
    @vitejs/plugin-vue-jsx: ^3.0.1 => 3.0.1
    vite: ^4.3.3 => 4.3.3
```

### Used Package Manager

pnpm

### Logs

<details>
<summary>Click to expand!</summary>

```shell
 vite:config bundled config file loaded in 327.28ms +0ms
  vite:config using resolved config: {
  vite:config   plugins: [
  vite:config     'vite:optimized-deps',
  vite:config     'vite:watch-package-data',
  vite:config     'vite:pre-alias',
  vite:config     'alias',
  vite:config     'vite:modulepreload-polyfill',
  vite:config     'vite:resolve',
  vite:config     'vite:html-inline-proxy',
  vite:config     'vite:css',
  vite:config     'vite:esbuild',
  vite:config     'vite:json',
  vite:config     'vite:wasm-helper',
  vite:config     'vite:worker',
  vite:config     'vite:asset',
  vite:config     'vite:vue',
  vite:config     'vite:vue-jsx',
  vite:config     'vite:wasm-fallback',
  vite:config     'vite:define',
  vite:config     'vite:css-post',
  vite:config     'vite:worker-import-meta-url',
  vite:config     'vite:asset-import-meta-url',
  vite:config     'vite:dynamic-import-vars',
  vite:config     'vite:import-glob',
  vite:config     'vite:client-inject',
  vite:config     'vite:import-analysis'
  vite:config   ],
  vite:config   resolve: {
  vite:config     mainFields: [ 'module', 'jsnext:main', 'jsnext' ],
  vite:config     browserField: true,
  vite:config     conditions: [],
  vite:config     extensions: [
  vite:config       '.mjs',  '.js',
  vite:config       '.mts',  '.ts',
  vite:config       '.jsx',  '.tsx',
  vite:config       '.json'
  vite:config     ],
  vite:config     dedupe: [ 'vue' ],
  vite:config     preserveSymlinks: false,
  vite:config     alias: [ [Object], [Object], [Object] ]
  vite:config   },
  vite:config   optimizeDeps: {
  vite:config     disabled: 'build',
  vite:config     force: undefined,
  vite:config     esbuildOptions: { preserveSymlinks: false }
  vite:config   },
  vite:config   server: {
  vite:config     preTransformRequests: true,
  vite:config     sourcemapIgnoreList: [Function: isInNodeModules],
  vite:config     middlewareMode: false,
  vite:config     fs: { strict: true, allow: [Array], deny: [Array] }
  vite:config   },
  vite:config   define: { __VUE_OPTIONS_API__: true, __VUE_PROD_DEVTOOLS__: false },
  vite:config   ssr: {
  vite:config     format: 'esm',
  vite:config     target: 'node',
  vite:config     external: [],
  vite:config     optimizeDeps: { disabled: true, esbuildOptions: [Object] }
  vite:config   },
  vite:config   esbuild: { jsxDev: true, include: /\.ts$/ },
  vite:config   configFile: 'C:/Users/jd/AppData/Local/Temp/volar-vue-playground/vite.config.ts',
  vite:config   configFileDependencies: [
  vite:config     'C:/Users/jd/AppData/Local/Temp/volar-vue-playground/vite.config.ts'
  vite:config   ],
  vite:config   inlineConfig: {
  vite:config     root: undefined,
  vite:config     base: undefined,
  vite:config     mode: undefined,
  vite:config     configFile: undefined,
  vite:config     logLevel: undefined,
  vite:config     clearScreen: undefined,
  vite:config     optimizeDeps: { force: undefined },
  vite:config     server: {}
  vite:config   },
  vite:config   root: 'C:/Users/jd/AppData/Local/Temp/volar-vue-playground',
  vite:config   base: '/',
  vite:config   rawBase: '/',
  vite:config   publicDir: 'C:\\Users\\jd\\AppData\\Local\\Temp\\volar-vue-playground\\public',
  vite:config   cacheDir: 'C:/Users/jd/AppData/Local/Temp/volar-vue-playground/node_modules/.vite',
  vite:config   command: 'serve',
  vite:config   mode: 'development',
  vite:config   isWorker: false,
  vite:config   mainConfig: null,
  vite:config   isProduction: false,
  vite:config   build: {
  vite:config     target: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
  vite:config     cssTarget: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
  vite:config     outDir: 'dist',
  vite:config     assetsDir: 'assets',
  vite:config     assetsInlineLimit: 4096,
  vite:config     cssCodeSplit: true,
  vite:config     sourcemap: false,
  vite:config     rollupOptions: {},
  vite:config     minify: 'esbuild',
  vite:config     terserOptions: {},
  vite:config     write: true,
  vite:config     emptyOutDir: null,
  vite:config     copyPublicDir: true,
  vite:config     manifest: false,
  vite:config     lib: false,
  vite:config     ssr: false,
  vite:config     ssrManifest: false,
  vite:config     ssrEmitAssets: false,
  vite:config     reportCompressedSize: true,
  vite:config     chunkSizeWarningLimit: 500,
  vite:config     watch: null,
  vite:config     commonjsOptions: { include: [Array], extensions: [Array] },
  vite:config     dynamicImportVarsOptions: { warnOnError: true, exclude: [Array] },
  vite:config     modulePreload: { polyfill: true },
  vite:config     cssMinify: true
  vite:config   },
  vite:config   preview: {
  vite:config     port: undefined,
  vite:config     strictPort: undefined,
  vite:config     host: undefined,
  vite:config     https: undefined,
  vite:config     open: undefined,
  vite:config     proxy: undefined,
  vite:config     cors: undefined,
  vite:config     headers: undefined
  vite:config   },
  vite:config   envDir: 'C:/Users/jd/AppData/Local/Temp/volar-vue-playground',
  vite:config   env: { BASE_URL: '/', MODE: 'development', DEV: true, PROD: false },
  vite:config   assetsInclude: [Function: assetsInclude],
  vite:config   logger: {
  vite:config     hasWarned: false,
  vite:config     info: [Function: info],
  vite:config     warn: [Function: warn],
  vite:config     warnOnce: [Function: warnOnce],
  vite:config     error: [Function: error],
  vite:config     clearScreen: [Function: clearScreen],
  vite:config     hasErrorLogged: [Function: hasErrorLogged]
  vite:config   },
  vite:config   packageCache: Map(1) {
  vite:config     'fnpd_C:/Users/jd/AppData/Local/Temp/volar-vue-playground' => {
  vite:config       dir: 'C:\\Users\\jd\\AppData\\Local\\Temp\\volar-vue-playground',
  vite:config       data: [Object],
  vite:config       hasSideEffects: [Function: hasSideEffects],
  vite:config       webResolvedImports: {},
  vite:config       nodeResolvedImports: {},
  vite:config       setResolvedCache: [Function: setResolvedCache],
  vite:config       getResolvedCache: [Function: getResolvedCache]
  vite:config     },
  vite:config     set: [Function (anonymous)]
  vite:config   },
  vite:config   createResolver: [Function: createResolver],
  vite:config   worker: {
  vite:config     format: 'iife',
  vite:config     plugins: [
  vite:config       'vite:optimized-deps',
  vite:config       'vite:watch-package-data',
  vite:config       'vite:pre-alias',
  vite:config       'alias',
  vite:config       'vite:modulepreload-polyfill',
  vite:config       'vite:resolve',
  vite:config       'vite:html-inline-proxy',
  vite:config       'vite:css',
  vite:config       'vite:esbuild',
  vite:config       'vite:json',
  vite:config       'vite:wasm-helper',
  vite:config       'vite:worker',
  vite:config       'vite:asset',
  vite:config       'vite:wasm-fallback',
  vite:config       'vite:define',
  vite:resolve 0.38ms /src/main.ts -> C:/Users/jd/AppData/Local/Temp/volar-vue-playground/src/main.ts +0ms
  vite:resolve 1.90ms vue -> C:/Users/jd/AppData/Local/Temp/volar-vue-playground/node_modules/.pnpm/vue@3.3.0-beta.2/node_modules/vue/dist/vue.runtime.esm-bundler.js +4ms
  vite:resolve 0.23ms ./App.vue -> C:/Users/jd/AppData/Local/Temp/volar-vue-playground/src/App.vue +1ms
  vite:resolve 0.35ms ./components/table/Table.vue -> C:/Users/jd/AppData/Local/Temp/volar-vue-playground/src/components/table/Table.vue +5ms
  vite:deps Scan completed in 54.83ms:
  vite:deps   vue -> C:/Users/jd/AppData/Local/Temp/volar-vue-playground/node_modules/.pnpm/vue@3.3.0-beta.2/node_modules/vue/dist/vue.runtime.esm-bundler.js +24ms
Error:   Failed to scan for dependencies from entries:
  C:/Users/jd/AppData/Local/Temp/volar-vue-playground/index.html

  X [ERROR] Unexpected "="

    script:C:/Users/jd/AppData/Local/Temp/volar-vue-playground/src/components/table/Table.vue?id=0:1:1:
      1 │  = Record<string, unknown>">
        ╵  ^


    at failureErrorWithLog (C:\Users\jd\AppData\Local\Temp\volar-vue-playground\node_modules\.pnpm\esbuild@0.17.18\node_modules\esbuild\lib\main.js:1636:15)
    at C:\Users\jd\AppData\Local\Temp\volar-vue-playground\node_modules\.pnpm\esbuild@0.17.18\node_modules\esbuild\lib\main.js:1048:25
    at runOnEndCallbacks (C:\Users\jd\AppData\Local\Temp\volar-vue-playground\node_modules\.pnpm\esbuild@0.17.18\node_modules\esbuild\lib\main.js:1471:45)
    at buildResponseToResult (C:\Users\jd\AppData\Local\Temp\volar-vue-playground\node_modules\.pnpm\esbuild@0.17.18\node_modules\esbuild\lib\main.js:1046:7)
    at C:\Users\jd\AppData\Local\Temp\volar-vue-playground\node_modules\.pnpm\esbuild@0.17.18\node_modules\esbuild\lib\main.js:1058:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (C:\Users\jd\AppData\Local\Temp\volar-vue-playground\node_modules\.pnpm\esbuild@0.17.18\node_modules\esbuild\lib\main.js:1057:54)
    at handleRequest (C:\Users\jd\AppData\Local\Temp\volar-vue-playground\node_modules\.pnpm\esbuild@0.17.18\node_modules\esbuild\lib\main.js:723:19)
    at handleIncomingPacket (C:\Users\jd\AppData\Local\Temp\volar-vue-playground\node_modules\.pnpm\esbuild@0.17.18\node_modules\esbuild\lib\main.js:745:7)
    at Socket.readFromStdout (C:\Users\jd\AppData\Local\Temp\volar-vue-playground\node_modules\.pnpm\esbuild@0.17.18\node_modules\esbuild\lib\main.js:673:7)
```

</details>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yyx990803** [comment] 2023-05-05 08:18
Ok this is an issue in Vite core's scanner, closing as duplicate of https://github.com/vuejs/core/issues/8171

**Closed by yyx990803** 2023-05-05 08:18 UTC
Labels: pending triage
