### ISSUE TITLE
Slots reactivity is not supported

### ISSUE THREAD

**Issue by PurpleTape** [vitejs/vite-plugin-vue#240] opened 2023-08-26 03:21 UTC
### Related plugins

- [ ] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [X] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

Sometimes there is a need to transfer a slot to the component, depending on the reactive value. 
In the syntax of SFC templates, this can be done as follows:

```vue
<template>
  <Comp>
    <template #slotName v-if="someReactiveVariable">
       Slot value
    </template>
  </Comp>
</template>
```

But when I try to do something like this in JSX, it lose the ability to reactively control the transfer of the slot to the component:

```ts
const render = () => (
  <Comp>
    {{
      slotName: someReactiveVariable.value ? () => 'Slot value' : undefined
    }}
  </Comp>
)
```

What to do in such a situation?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-t9skwh?file=src%2FApp.tsx

### Steps to reproduce

Click "Toggle useSlot" button

### System Info

```shell
"@vitejs/plugin-vue-jsx": "^3.0.2"
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by edison1105** [comment] 2024-09-24 06:08
Closing as it can't reproduce with the latest version.
see [Playground](https://play.vuejs.org/#eNqNU02P0zAQ/SuDL22lKj3AqaRFsNoDSEBF9+hLSKclu64d2U4pqvLfmbGdLwQVvTSZeTPz5r3JTbyv6+zSoFiL3JW2qj049E29lbo618Z62BUWtYejNWeYZav4mnl3nUmdr2INoXOP51oVHvk5grZ5QnNo1efFUnhXGn2sTtmzM5pG36QGkKI057pSaL/WvjLaSbGGkOFcoZT5+SnEvG1w2cXLH1i+/CX+7K4ck2Jn0aG9oBR9zhf2hD6mH/df8ErPffJsDo0i9J3kN3RGNcwxwj40+kC0R7jA9mMQsNKnJ/d49ahdtxQTZWQb8FKQ/g93Vh/ovs7ehDqpW1KRa9gIEjB5dYMDHisduhnNtrXJOBoxeyu11HgNSMIVjQr/Y/yc289ra2q3pG5OGe+gXcBm29GxdB1Ww5xjMQIRlnmSCt5BaBF/+XZPGagcNA4PtNEAnC/afNU3WMB6WrcjBqO6QCjUTapooU7ExC4Ae+kAuGQNe2/JhWROxJOEXE4qDgd9R8cl7X38U8wE/vxrkLv7Sjpr/kvzoGXkTJ+F87x1EG7DU+fHQjlksgwYy99JlveK5N8b740Gox9UVb5sbgmXGmaXQjVIbV9NAou2bwDwZE4nhR0FknICzbyJYpJ//dBVnEpNBh4W2Kd/vo81Y482UrB1EIZIMeJz670c/JyuQycXtpzxdcUOM7on+iaDzofke/B+RHpEIY1Lp8VSt+E42t/F5KNb)

**Closed by edison1105** 2024-09-24 06:08 UTC
Labels: cannot reproduce
