### ISSUE TITLE
Sourcemap to Vue SFC doesn't work on first load

### ISSUE THREAD

**Issue by richardsimko** [vitejs/vite-plugin-vue#131] opened 2023-03-13 12:35 UTC
### Describe the bug

When initially loading a page that contains Vue Single File Components which reference an external template

```
<template src="./HelloWorld-template.html" />
```

the sourcemap only sourcemaps the template on the first load. If I edit the file and thus let the HMR reload it the sourcemap then maps to the SFC as it should.

![image](https://user-images.githubusercontent.com/1245031/224694167-8b3d9431-c66c-436c-a784-298a2561ac5b.png)
Initial load

![image](https://user-images.githubusercontent.com/1245031/224694087-d1db6bfa-01ce-4386-a79b-322c57764166.png)
After saving the file and triggering a reload with HMR.

### Reproduction

https://github.com/richardsimko/vite-vue-sourcemap-issues

### Steps to reproduce

1. Run `yarn install ` and `yarn run dev` to start the server. 
2. Load the site and open HelloWorld.vue in Chrome devtools
3. Observe that it's only the template
4. Make a change to `HelloWorld.vue`
5. Observe that the file now changes in devtools to reflect the contents of the SFC

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 87.84 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - ~/.n/bin/node
    Yarn: 1.22.19 - ~/.n/bin/yarn
    npm: 9.2.0 - ~/.n/bin/npm
  Browsers:
    Chrome: 110.0.5481.77
    Safari: 16.3
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
    vite: ^4.1.4 => 4.1.4
```

### Used Package Manager

yarn

### Logs

<details>
<summary>Click to expand!</summary>

```shell
vite:config bundled config file loaded in 48.49ms +0ms
  vite:esbuild init tsconfck (root: /Users/richard/git/vite-vue-sourcemap-issue) +0ms
  vite:esbuild init tsconfck (root: /Users/richard/git/vite-vue-sourcemap-issue) +0ms
  vite:esbuild init tsconfck end +1ms
  vite:esbuild init tsconfck end +0ms
  vite:config using resolved config: {
  vite:config   plugins: [
  vite:config     'vite:pre-alias',
  vite:config     'alias',
  vite:config     'vite:modulepreload-polyfill',
  vite:config     'vite:optimized-deps',
  vite:config     'vite:resolve',
  vite:config     'vite:html-inline-proxy',
  vite:config     'vite:css',
  vite:config     'vite:esbuild',
  vite:config     'vite:json',
  vite:config     'vite:wasm-helper',
  vite:config     'vite:worker',
  vite:config     'vite:asset',
  vite:config     'vite:vue',
  vite:config     'vite:wasm-fallback',
  vite:config     'vite:define',
  vite:config     'vite:css-post',
  vite:config     'vite:worker-import-meta-url',
  vite:config     'vite:asset-import-meta-url',
  vite:config     'vite:dynamic-import-vars',
  vite:config     'vite:import-glob',
  vite:config     'vite:client-inject',
  vite:config     'vite:import-analysis'
  vite:config   ],
  vite:config   resolve: {
  vite:config     mainFields: [ 'module', 'jsnext:main', 'jsnext' ],
  vite:config     browserField: true,
  vite:config     conditions: [],
  vite:config     extensions: [
  vite:config       '.mjs',  '.js',
  vite:config       '.mts',  '.ts',
  vite:config       '.jsx',  '.tsx',
  vite:config       '.json'
  vite:config     ],
  vite:config     dedupe: [ 'vue' ],
  vite:config     preserveSymlinks: false,
  vite:config     alias: [ [Object], [Object], [Object] ]
  vite:config   },
  vite:config   optimizeDeps: {
  vite:config     disabled: 'build',
  vite:config     force: undefined,
  vite:config     esbuildOptions: { preserveSymlinks: false }
  vite:config   },
  vite:config   server: {
  vite:config     preTransformRequests: true,
  vite:config     middlewareMode: false,
  vite:config     fs: { strict: true, allow: [Array], deny: [Array] }
  vite:config   },
  vite:config   define: { __VUE_OPTIONS_API__: true, __VUE_PROD_DEVTOOLS__: false },
  vite:config   ssr: {
  vite:config     format: 'esm',
  vite:config     target: 'node',
  vite:config     external: [],
  vite:config     optimizeDeps: { disabled: true, esbuildOptions: [Object] }
  vite:config   },
  vite:config   configFile: '/Users/richard/git/vite-vue-sourcemap-issue/vite.config.ts',
  vite:config   configFileDependencies: [ '/Users/richard/git/vite-vue-sourcemap-issue/vite.config.ts' ],
  vite:config   inlineConfig: {
  vite:config     root: undefined,
  vite:config     base: undefined,
  vite:config     mode: undefined,
  vite:config     configFile: undefined,
  vite:config     logLevel: undefined,
  vite:config     clearScreen: undefined,
  vite:config     optimizeDeps: { force: undefined },
  vite:config     server: {}
  vite:config   },
  vite:config   root: '/Users/richard/git/vite-vue-sourcemap-issue',
  vite:config   base: '/',
  vite:config   rawBase: '/',
  vite:config   publicDir: '/Users/richard/git/vite-vue-sourcemap-issue/public',
  vite:config   cacheDir: '/Users/richard/git/vite-vue-sourcemap-issue/node_modules/.vite',
  vite:config   command: 'serve',
  vite:config   mode: 'development',
  vite:config   isWorker: false,
  vite:config   mainConfig: null,
  vite:config   isProduction: false,
  vite:config   build: {
  vite:config     target: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
  vite:config     cssTarget: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
  vite:config     outDir: 'dist',
  vite:config     assetsDir: 'assets',
  vite:config     assetsInlineLimit: 4096,
  vite:config     cssCodeSplit: true,
  vite:config     sourcemap: false,
  vite:config     rollupOptions: {},
  vite:config     minify: 'esbuild',
  vite:config     terserOptions: {},
  vite:config     write: true,
  vite:config     emptyOutDir: null,
  vite:config     copyPublicDir: true,
  vite:config     manifest: false,
  vite:config     lib: false,
  vite:config     ssr: false,
  vite:config     ssrManifest: false,
  vite:config     ssrEmitAssets: false,
  vite:config     reportCompressedSize: true,
  vite:config     chunkSizeWarningLimit: 500,
  vite:config     watch: null,
  vite:config     commonjsOptions: { include: [Array], extensions: [Array] },
  vite:config     dynamicImportVarsOptions: { warnOnError: true, exclude: [Array] },
  vite:config     modulePreload: { polyfill: true }
  vite:config   },
  vite:config   preview: {
  vite:config     port: undefined,
  vite:config     strictPort: undefined,
  vite:config     host: undefined,
  vite:config     https: undefined,
  vite:config     open: undefined,
  vite:config     proxy: undefined,
  vite:config     cors: undefined,
  vite:config     headers: undefined
  vite:config   },
  vite:config   env: { BASE_URL: '/', MODE: 'development', DEV: true, PROD: false },
  vite:config   assetsInclude: [Function: assetsInclude],
  vite:config   logger: {
  vite:config     hasWarned: false,
  vite:config     info: [Function: info],
  vite:config     warn: [Function: warn],
  vite:config     warnOnce: [Function: warnOnce],
  vite:config     error: [Function: error],
  vite:config     clearScreen: [Function: clearScreen],
  vite:config     hasErrorLogged: [Function: hasErrorLogged]
  vite:config   },
  vite:config   packageCache: Map(0) {},
  vite:config   createResolver: [Function: createResolver],
  vite:config   worker: {
  vite:config     format: 'iife',
  vite:config     plugins: [
  vite:config       'vite:pre-alias',
  vite:config       'alias',
  vite:config       'vite:modulepreload-polyfill',
  vite:config       'vite:optimized-deps',
  vite:config       'vite:resolve',
  vite:config       'vite:html-inline-proxy',
  vite:config       'vite:css',
  vite:config       'vite:esbuild',
  vite:config       'vite:json',
  vite:config       'vite:wasm-helper',
  vite:config       'vite:worker',
  vite:config       'vite:asset',
  vite:config       'vite:wasm-fallback',
  vite:config       'vite:define',
  vite:config       'vite:css-post',
  vite:config       'vite:worker-import-meta-url',
  vite:config       'vite:asset-import-meta-url',
  vite:config       'vite:dynamic-import-vars',
  vite:config       'vite:import-glob',
  vite:config       'vite:client-inject',
  vite:config       'vite:import-analysis'
  vite:config     ],
  vite:config     rollupOptions: {},
  vite:config     getSortedPlugins: [Function: getSortedPlugins],
  vite:config     getSortedPluginHooks: [Function: getSortedPluginHooks]
  vite:config   },
  vite:config   appType: 'spa',
  vite:config   experimental: { importGlobRestoreExtension: false, hmrPartialAccept: false },
  vite:config   getSortedPlugins: [Function: getSortedPlugins],
  vite:config   getSortedPluginHooks: [Function: getSortedPluginHooks]
  vite:config } +4ms
  vite:deps Hash is consistent. Skipping. Use --force to override. +0ms

  VITE v4.1.4  ready in 198 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
  vite:html-fallback Rewriting GET / to /index.html +0ms
  vite:time 15.36ms /index.html +0ms
  vite:html-fallback Rewriting GET / to /index.html +36ms
  vite:time 1.77ms /index.html +23ms
  vite:resolve 1.03ms /@vite/client -> /Users/richard/git/vite-vue-sourcemap-issue/node_modules/vite/dist/client/client.mjs +0ms
  vite:resolve 0.28ms /src/main.ts -> /Users/richard/git/vite-vue-sourcemap-issue/src/main.ts +2ms
  vite:load 0.74ms [fs] /src/main.ts +0ms
  vite:load 3.84ms [fs] /@vite/client +2ms
  vite:resolve 0.33ms @vite/env -> /Users/richard/git/vite-vue-sourcemap-issue/node_modules/vite/dist/client/env.mjs +23ms
  vite:resolve 0.08ms /node_modules/vite/dist/client/env.mjs -> /Users/richard/git/vite-vue-sourcemap-issue/node_modules/vite/dist/client/env.mjs +0ms
  vite:import-analysis 2.41ms [1 imports rewritten] node_modules/vite/dist/client/client.mjs +0ms
  vite:transform 17.63ms /@vite/client +0ms
  vite:time 27.54ms /@vite/client +43ms
  vite:resolve 0.30ms vue -> /Users/richard/git/vite-vue-sourcemap-issue/node_modules/.vite/deps/vue.js?v=d69ef606 +5ms
  vite:resolve 0.18ms /node_modules/.vite/deps/vue.js?v=d69ef606 -> /Users/richard/git/vite-vue-sourcemap-issue/node_modules/.vite/deps/vue.js?v=d69ef606 +1ms
  vite:resolve 1.00ms ./App.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/App.vue +1ms
  vite:resolve 0.08ms /src/App.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/App.vue +1ms
  vite:resolve 0.09ms ./assets/main.css -> /Users/richard/git/vite-vue-sourcemap-issue/src/assets/main.css +0ms
  vite:resolve 0.07ms /src/assets/main.css -> /Users/richard/git/vite-vue-sourcemap-issue/src/assets/main.css +0ms
  vite:import-analysis 4.29ms [3 imports rewritten] src/main.ts +9ms
  vite:transform 29.86ms /src/main.ts +9ms
  vite:time 32.44ms /src/main.ts +8ms
  vite:optimize-deps load /Users/richard/git/vite-vue-sourcemap-issue/node_modules/.vite/deps/vue.js +0ms
  vite:load 8.21ms [fs] /node_modules/vite/dist/client/env.mjs +31ms
  vite:load 1.36ms [fs] /src/App.vue +0ms
  vite:load 21.49ms [fs] /src/assets/main.css +20ms
  vite:load 22.82ms [plugin] /node_modules/.vite/deps/vue.js?v=d69ef606 +1ms
  vite:import-analysis 2.10ms [no imports] node_modules/.vite/deps/vue.js?v=d69ef606 +27ms
  vite:transform 3.08ms /node_modules/.vite/deps/vue.js?v=d69ef606 +27ms
  vite:time 5.50ms /node_modules/.vite/deps/vue.js?v=d69ef606 +27ms
  vite:import-analysis 1.07ms [no imports] node_modules/vite/dist/client/env.mjs +2ms
  vite:transform 6.08ms /node_modules/vite/dist/client/env.mjs +2ms
  vite:time 28.09ms /node_modules/vite/dist/client/env.mjs +2ms
  vite:resolve 0.20ms ./components/HelloWorld.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/HelloWorld.vue +37ms
  vite:resolve 0.05ms /src/components/HelloWorld.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/HelloWorld.vue +0ms
  vite:resolve 0.06ms ./components/TheWelcome.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/TheWelcome.vue +0ms
  vite:resolve 0.57ms /src/components/TheWelcome.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/TheWelcome.vue +0ms
  vite:resolve 0.19ms /src/App.vue?vue&type=style&index=0&scoped=7a7a37b1&lang.css -> /Users/richard/git/vite-vue-sourcemap-issue/src/App.vue?vue&type=style&index=0&scoped=7a7a37b1&lang.css +2ms
  vite:hmr [self-accepts] src/App.vue +0ms
  vite:import-analysis 4.37ms [5 imports rewritten] src/App.vue +11ms
  vite:transform 37.74ms /src/App.vue +11ms
  vite:cache [memory] /node_modules/.vite/deps/vue.js?v=d69ef606 +0ms
  vite:load 0.25ms [plugin] /src/App.vue?vue&type=style&index=0&scoped=7a7a37b1&lang.css +18ms
  vite:load 0.50ms [plugin] plugin-vue:export-helper +0ms
  vite:import-analysis 0.02ms [no imports] plugin-vue:export-helper +1ms
  vite:transform 0.07ms plugin-vue:export-helper +1ms
  vite:load 2.71ms [fs] /src/components/TheWelcome.vue +2ms
  vite:load 19.63ms [fs] /src/components/HelloWorld.vue +17ms
  vite:resolve 0.15ms ./HelloWorld-template.html -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/HelloWorld-template.html +27ms
  vite:time 38.10ms /src/App.vue +37ms
  vite:resolve 0.11ms ./HelloWorld-template.html?vue&type=template&src=e17ea971&scoped=e17ea971&lang.js -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/HelloWorld-template.html?vue&type=template&src=e17ea971&scoped=e17ea971&lang.js +2ms
  vite:resolve 0.06ms /src/components/HelloWorld-template.html?vue&type=template&src=e17ea971&scoped=e17ea971&lang.js -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/HelloWorld-template.html?vue&type=template&src=e17ea971&scoped=e17ea971&lang.js +1ms
  vite:resolve 0.08ms /src/components/HelloWorld.vue?vue&type=style&index=0&scoped=e17ea971&lang.css -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/HelloWorld.vue?vue&type=style&index=0&scoped=e17ea971&lang.css +0ms
  vite:hmr [self-accepts] src/components/HelloWorld.vue +29ms
  vite:import-analysis 1.19ms [4 imports rewritten] src/components/HelloWorld.vue +27ms
  vite:transform 8.17ms /src/components/HelloWorld.vue +27ms
  vite:cache [memory] /node_modules/.vite/deps/vue.js?v=d69ef606 +29ms
  vite:cache [memory] plugin-vue:export-helper +0ms
  vite:load 0.47ms [plugin] /src/components/HelloWorld-template.html?vue&type=template&src=e17ea971&scoped=e17ea971&lang.js +9ms
  vite:load 0.48ms [plugin] /src/components/HelloWorld.vue?vue&type=style&index=0&scoped=e17ea971&lang.css +1ms
  vite:hmr [self-accepts] src/components/HelloWorld-template.html?vue&type=template&src=e17ea971&scoped=e17ea971&lang.js +4ms
  vite:import-analysis 0.27ms [1 imports rewritten] src/components/HelloWorld-template.html?vue&type=template&src=e17ea971&scoped=e17ea971&lang.js +4ms
  vite:transform 1.68ms /src/components/HelloWorld-template.html?vue&type=template&src=e17ea971&scoped=e17ea971&lang.js +4ms
  vite:cache [memory] /node_modules/.vite/deps/vue.js?v=d69ef606 +3ms
  vite:cache [memory] plugin-vue:export-helper +1ms
  vite:time 0.15ms /@id/__x00__plugin-vue:export-helper +7ms
  vite:resolve 0.09ms ./WelcomeItem.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/WelcomeItem.vue +7ms
  vite:resolve 0.05ms /src/components/WelcomeItem.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/WelcomeItem.vue +0ms
  vite:resolve 0.06ms ./icons/IconDocumentation.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/icons/IconDocumentation.vue +0ms
  vite:resolve 0.04ms /src/components/icons/IconDocumentation.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/icons/IconDocumentation.vue +0ms
  vite:resolve 0.16ms ./icons/IconTooling.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/icons/IconTooling.vue +0ms
  vite:resolve 0.04ms /src/components/icons/IconTooling.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/icons/IconTooling.vue +0ms
  vite:resolve 0.05ms ./icons/IconEcosystem.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/icons/IconEcosystem.vue +0ms
  vite:resolve 0.06ms /src/components/icons/IconEcosystem.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/icons/IconEcosystem.vue +0ms
  vite:resolve 0.05ms ./icons/IconCommunity.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/icons/IconCommunity.vue +0ms
  vite:resolve 0.04ms /src/components/icons/IconCommunity.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/icons/IconCommunity.vue +1ms
  vite:resolve 0.05ms ./icons/IconSupport.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/icons/IconSupport.vue +0ms
  vite:resolve 0.04ms /src/components/icons/IconSupport.vue -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/icons/IconSupport.vue +0ms
  vite:hmr [self-accepts] src/components/TheWelcome.vue +4ms
  vite:import-analysis 1.95ms [8 imports rewritten] src/components/TheWelcome.vue +4ms
  vite:transform 32.78ms /src/components/TheWelcome.vue +4ms
  vite:cache [memory] /node_modules/.vite/deps/vue.js?v=d69ef606 +4ms
  vite:cache [memory] plugin-vue:export-helper +0ms
  vite:time 5.68ms /src/components/HelloWorld.vue +5ms
  vite:load 3.11ms [fs] /src/components/WelcomeItem.vue +10ms
  vite:resolve 0.05ms /src/components/WelcomeItem.vue?vue&type=style&index=0&scoped=bd9b3c35&lang.css -> /Users/richard/git/vite-vue-sourcemap-issue/src/components/WelcomeItem.vue?vue&type=style&index=0&scoped=bd9b3c35&lang.css +6ms
  vite:hmr [self-accepts] src/components/WelcomeItem.vue +7ms
  vite:import-analysis 0.78ms [3 imports rewritten] src/components/WelcomeItem.vue +7ms
  vite:transform 2.50ms /src/components/WelcomeItem.vue +7ms
  vite:cache [memory] /node_modules/.vite/deps/vue.js?v=d69ef606 +6ms
  vite:cache [memory] plugin-vue:export-helper +0ms
  vite:load 0.03ms [plugin] /src/components/WelcomeItem.vue?vue&type=style&index=0&scoped=bd9b3c35&lang.css +3ms
  vite:load 6.38ms [fs] /src/components/icons/IconTooling.vue +0ms
  vite:hmr [self-accepts] src/components/icons/IconTooling.vue +2ms
  vite:import-analysis 0.28ms [2 imports rewritten] src/components/icons/IconTooling.vue +2ms
  vite:transform 1.61ms /src/components/icons/IconTooling.vue +2ms
  vite:cache [memory] /node_modules/.vite/deps/vue.js?v=d69ef606 +2ms
  vite:cache [memory] plugin-vue:export-helper +0ms
  vite:load 8.17ms [fs] /src/components/icons/IconEcosystem.vue +2ms
  vite:hmr [self-accepts] src/components/icons/IconEcosystem.vue +3ms
  vite:import-analysis 0.43ms [2 imports rewritten] src/components/icons/IconEcosystem.vue +3ms
  vite:transform 3.24ms /src/components/icons/IconEcosystem.vue +3ms
  vite:cache [memory] /node_modules/.vite/deps/vue.js?v=d69ef606 +4ms
  vite:cache [memory] plugin-vue:export-helper +0ms
  vite:load 12.37ms [fs] /src/components/icons/IconDocumentation.vue +4ms
  vite:hmr [self-accepts] src/components/icons/IconDocumentation.vue +3ms
  vite:import-analysis 0.31ms [2 imports rewritten] src/components/icons/IconDocumentation.vue +3ms
  vite:transform 1.70ms /src/components/icons/IconDocumentation.vue +3ms
  vite:cache [memory] /node_modules/.vite/deps/vue.js?v=d69ef606 +2ms
  vite:cache [memory] plugin-vue:export-helper +0ms
  vite:load 14.53ms [fs] /src/components/icons/IconSupport.vue +3ms
  vite:hmr [self-accepts] src/components/icons/IconSupport.vue +2ms
  vite:import-analysis 0.57ms [2 imports rewritten] src/components/icons/IconSupport.vue +2ms
  vite:transform 1.20ms /src/components/icons/IconSupport.vue +2ms
  vite:cache [memory] /node_modules/.vite/deps/vue.js?v=d69ef606 +2ms
  vite:cache [memory] plugin-vue:export-helper +0ms
  vite:load 16.00ms [fs] /src/components/icons/IconCommunity.vue +1ms
  vite:hmr [self-accepts] src/components/icons/IconCommunity.vue +1ms
  vite:import-analysis 0.24ms [2 imports rewritten] src/components/icons/IconCommunity.vue +1ms
  vite:transform 1.38ms /src/components/icons/IconCommunity.vue +1ms
  vite:cache [memory] /node_modules/.vite/deps/vue.js?v=d69ef606 +2ms
  vite:cache [memory] plugin-vue:export-helper +0ms
  vite:time 22.30ms /src/components/TheWelcome.vue +17ms
  vite:cache [memory] /src/components/HelloWorld-template.html?vue&type=template&src=e17ea971&scoped=e17ea971&lang.js +0ms
  vite:time 0.19ms /src/components/HelloWorld-template.html?import&vue&type=template&src=e17ea971&scoped=e17ea971&lang.js +0ms
  vite:cache [memory] /src/components/icons/IconDocumentation.vue +5ms
  vite:time 0.49ms /src/components/icons/IconDocumentation.vue +5ms
  vite:cache [memory] /src/components/WelcomeItem.vue +1ms
  vite:time 0.19ms /src/components/WelcomeItem.vue +1ms
  vite:cache [memory] /src/components/icons/IconTooling.vue +0ms
  vite:time 0.18ms /src/components/icons/IconTooling.vue +0ms
  vite:cache [memory] /src/components/icons/IconEcosystem.vue +1ms
  vite:time 0.24ms /src/components/icons/IconEcosystem.vue +1ms
  vite:cache [memory] /src/components/icons/IconCommunity.vue +0ms
  vite:time 0.14ms /src/components/icons/IconCommunity.vue +0ms
  vite:cache [memory] /src/components/icons/IconSupport.vue +3ms
  vite:time 0.35ms /src/components/icons/IconSupport.vue +3ms
  vite:hmr [self-accepts] src/App.vue?vue&type=style&index=0&scoped=7a7a37b1&lang.css +19ms
  vite:import-analysis 0.10ms [0 imports rewritten] src/App.vue?vue&type=style&index=0&scoped=7a7a37b1&lang.css +19ms
  vite:transform 71.72ms /src/App.vue?vue&type=style&index=0&scoped=7a7a37b1&lang.css +19ms
  vite:time 40.24ms /src/App.vue?vue&type=style&index=0&scoped=7a7a37b1&lang.css +8ms
  vite:hmr [self-accepts] src/components/HelloWorld.vue?vue&type=style&index=0&scoped=e17ea971&lang.css +3ms
  vite:import-analysis 0.06ms [0 imports rewritten] src/components/HelloWorld.vue?vue&type=style&index=0&scoped=e17ea971&lang.css +3ms
  vite:transform 46.31ms /src/components/HelloWorld.vue?vue&type=style&index=0&scoped=e17ea971&lang.css +3ms
  vite:time 21.01ms /src/components/HelloWorld.vue?vue&type=style&index=0&scoped=e17ea971&lang.css +3ms
  vite:hmr [self-accepts] src/components/WelcomeItem.vue?vue&type=style&index=0&scoped=bd9b3c35&lang.css +4ms
  vite:import-analysis 0.07ms [0 imports rewritten] src/components/WelcomeItem.vue?vue&type=style&index=0&scoped=bd9b3c35&lang.css +4ms
  vite:transform 36.41ms /src/components/WelcomeItem.vue?vue&type=style&index=0&scoped=bd9b3c35&lang.css +4ms
  vite:time 14.18ms /src/components/WelcomeItem.vue?vue&type=style&index=0&scoped=bd9b3c35&lang.css +4ms
  vite:resolve 0.78ms ./base.css -> /Users/richard/git/vite-vue-sourcemap-issue/src/assets/base.css +0ms
  vite:hmr [self-accepts] src/assets/main.css +5ms
  vite:import-analysis 0.06ms [0 imports rewritten] src/assets/main.css +5ms
  vite:transform 102.72ms /src/assets/main.css +5ms
  vite:time 97.09ms /src/assets/main.css +5ms
  vite:time 1.74ms /node_modules/.vite/deps/vue.js.map +9ms
  vite:time 4.10ms /src/assets/logo.svg +18ms
  vite:time 2.23ms /favicon.ico +11ms
  vite:deps ✨ static imports crawl ended +1s
  vite:hmr [file change] src/components/HelloWorld.vue +26s
12:55:08 PM [vite] hmr update /src/components/HelloWorld.vue
  vite:load 0.21ms [fs] /src/components/HelloWorld.vue +26s
  vite:hmr [self-accepts] src/components/HelloWorld.vue +29ms
  vite:import-analysis 1.12ms [4 imports rewritten] src/components/HelloWorld.vue +26s
  vite:transform 4.12ms /src/components/HelloWorld.vue +26s
  vite:time 5.41ms /src/components/HelloWorld.vue +26s
  vite:cache [memory] /node_modules/.vite/deps/vue.js?v=d69ef606 +26s
  vite:cache [memory] /src/components/HelloWorld-template.html?vue&type=template&src=e17ea971&scoped=e17ea971&lang.js +0ms
  vite:cache [memory] plugin-vue:export-helper +0ms
  vite:load 0.05ms [plugin] /src/components/HelloWorld.vue?vue&type=style&index=0&scoped=e17ea971&lang.css +6ms
  vite:hmr [self-accepts] src/components/HelloWorld.vue?vue&type=style&index=0&scoped=e17ea971&lang.css +3ms
  vite:import-analysis 0.07ms [0 imports rewritten] src/components/HelloWorld.vue?vue&type=style&index=0&scoped=e17ea971&lang.css +3ms
  vite:transform 1.33ms /src/components/HelloWorld.vue?vue&type=style&index=0&scoped=e17ea971&lang.css +2ms
```
</details>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment] 2023-03-13 16:39
Duplicate of https://github.com/vitejs/vite-plugin-vue/issues/130

**Closed by sapphi-red** 2023-03-13 16:39 UTC
Labels: pending triage

**Comment by richardsimko** [comment] 2023-03-14 20:23
Oh sorry!
